use super::*;

pub(crate) fn intl_plural_rules_pool_strings() -> Vec<String> {
    [
        "Intl.PluralRules",
        "PluralRules",
        "supportedLocalesOf",
        "resolvedOptions",
        "select",
        "selectRange",
        "locale",
        "type",
        "notation",
        "compactDisplay",
        "minimumIntegerDigits",
        "minimumFractionDigits",
        "maximumFractionDigits",
        "minimumSignificantDigits",
        "maximumSignificantDigits",
        "roundingIncrement",
        "roundingMode",
        "roundingPriority",
        "trailingZeroDisplay",
        "pluralCategories",
        "cardinal",
        "ordinal",
        "standard",
        "compact",
        "scientific",
        "engineering",
        "short",
        "long",
        "best fit",
        "lookup",
        "localeMatcher",
        "zero",
        "one",
        "two",
        "few",
        "many",
        "other",
        "Invalid localeMatcher option",
        "Invalid type option",
        "Invalid notation option",
        "Invalid compactDisplay option",
        PR_RECEIVER_ERROR,
        PR_INVALID_OPTION,
        PR_MUST_USE_NEW,
        PR_RANGE_UNDEFINED,
    ]
    .into_iter()
    .map(str::to_owned)
    .collect()
}
