use super::*;

pub(crate) fn intl_relative_time_format_pool_strings() -> Vec<String> {
    let mut strings: Vec<_> = [
        "Intl.RelativeTimeFormat",
        "RelativeTimeFormat",
        "supportedLocalesOf",
        "resolvedOptions",
        "format",
        "formatToParts",
        "locale",
        "style",
        "numeric",
        "numberingSystem",
        "value",
        "unit",
        "",
        "-0",
        "lookup",
        "best fit",
        "long",
        "short",
        "narrow",
        "always",
        "auto",
        "approximatelySign",
        "compact",
        "currency",
        "decimal",
        "exponentInteger",
        "exponentMinusSign",
        "exponentSeparator",
        "fraction",
        "group",
        "infinity",
        "integer",
        "literal",
        "minusSign",
        "nan",
        "percentSign",
        "plusSign",
        "second",
        "seconds",
        "minute",
        "minutes",
        "hour",
        "hours",
        "day",
        "days",
        "week",
        "weeks",
        "month",
        "months",
        "quarter",
        "quarters",
        "year",
        "years",
        "Invalid localeMatcher option",
        "Invalid style option",
        "Invalid numeric option",
        RTF_RECEIVER_ERROR,
        RTF_INVALID_OPTION,
        RTF_NON_FINITE,
        RTF_INVALID_UNIT,
        "Intl.RelativeTimeFormat must be called with new",
    ]
    .into_iter()
    .map(str::to_owned)
    .collect();
    strings.push("Invalid numberingSystem option".to_owned());
    strings
}
