//! ECMA-402 15.5.6-15.5.17 (Locale information) and 8.3.2 (supportedValuesOf)
//! over the pinned CLDR47 and IANA2026a tables generated by
//! `scripts/generate-intl-locale-info.py`.

use icu_locale::{LocaleCanonicalizer, LocaleExpander};

use crate::number_format::options::SingleUnit;
use crate::number_format::{default_numbering_system_by_prefix, NumberProfiles};
use crate::{
    CanonicalLocaleId, DateTimeCalendar, DateTimeHourCycle, IsoWeekday, LocaleId, LocaleInfoError,
    LocaleInfoQuery, LocaleInfoRequest, LocaleInfoResult, LocaleTransformError, SupportedValuesKey,
    SupportedValuesResult, TextDirection, WeekInfo,
};

use super::language_domain::{LikelySubtags, ParsedLocale, ReservedLanguageAliasRules};
use super::named_time_zones::NamedTimeZones;

// Generated tables keep one row per line; rustfmt would reflow them away from
// the generator's `--check` output.
#[rustfmt::skip]
mod generated;

pub(super) const PROVIDER_DATA_SHA256: [u8; 32] = generated::PROVIDER_DATA_SHA256;

/// ECMA-402 15.5.10 step 3.b: CollationsOfLocale without a Collator match.
const UNMATCHED_COLLATIONS: &[&str] = &["emoji", "eor"];
/// ECMA-402 15.5.9 step 9 and 15.5.11 step 9 defaults.
const DEFAULT_CALENDAR: &str = "gregory";
const DEFAULT_HOUR_CYCLE: DateTimeHourCycle = DateTimeHourCycle::H23;
/// ECMA-402 15.5.12 step 4: NumberingSystemsOfLocale without a match.
const UNMATCHED_NUMBERING_SYSTEM: &str = "latn";
const WORLD: &str = "001";

/// One region's CLDR week data after per-field resolution against 001.
#[derive(Debug, Clone, Copy)]
struct WeekRow {
    first_day: IsoWeekday,
    weekend: &'static [IsoWeekday],
}

fn table_lookup<T: Copy>(table: &[(&str, T)], key: &str) -> Option<T> {
    table
        .binary_search_by(|(candidate, _)| (*candidate).cmp(key))
        .ok()
        .map(|index| table[index].1)
}

/// The subtags of a canonical Unicode locale identifier that ECMA-402's
/// GetLocale* operations and UnicodeExtensionValue read.
struct LocaleView<'a> {
    tag: &'a str,
    language: &'a str,
    script: Option<&'a str>,
    region: Option<&'a str>,
    /// Byte range of the `-u-...` sequence including its leading separator.
    unicode_extension: Option<(usize, usize)>,
}

impl<'a> LocaleView<'a> {
    fn parse(tag: &'a str) -> Result<Self, LocaleInfoError> {
        let mut subtags = Vec::new();
        let mut start = 0;
        for subtag in tag.split('-') {
            subtags.push((start, subtag));
            start += subtag.len() + 1;
        }
        let (_, language) = subtags[0];
        if !(2..=8).contains(&language.len()) || !language.bytes().all(|b| b.is_ascii_lowercase()) {
            return Err(LocaleInfoError::InvalidLocale("language subtag"));
        }
        let mut script = None;
        let mut region = None;
        let mut index = 1;
        let mut variants = false;
        while index < subtags.len() && subtags[index].1.len() > 1 {
            let subtag = subtags[index].1;
            if !variants && script.is_none() && region.is_none() && subtag.len() == 4 {
                let bytes = subtag.as_bytes();
                if bytes.iter().all(u8::is_ascii_alphabetic) {
                    script = Some(subtag);
                    index += 1;
                    continue;
                }
            }
            if !variants
                && region.is_none()
                && ((subtag.len() == 2 && subtag.bytes().all(|b| b.is_ascii_uppercase()))
                    || (subtag.len() == 3 && subtag.bytes().all(|b| b.is_ascii_digit())))
            {
                region = Some(subtag);
                index += 1;
                continue;
            }
            variants = true;
            index += 1;
        }
        let mut unicode_extension = None;
        while index < subtags.len() {
            let (offset, singleton) = subtags[index];
            if singleton.len() != 1 {
                return Err(LocaleInfoError::InvalidLocale("extension structure"));
            }
            if singleton == "x" {
                break;
            }
            let mut end = index + 1;
            while end < subtags.len() && subtags[end].1.len() > 1 {
                end += 1;
            }
            if singleton == "u" {
                let finish = subtags.get(end).map_or(tag.len(), |(next, _)| next - 1);
                unicode_extension = Some((offset - 1, finish));
            }
            index = end;
        }
        Ok(Self {
            tag,
            language,
            script,
            region,
            unicode_extension,
        })
    }

    /// UnicodeExtensionValue (15.5.6): `None` is the spec's `empty`; a present
    /// keyword without a type yields the empty String.
    fn keyword(&self, key: &str) -> Option<&'a str> {
        let (start, end) = self.unicode_extension?;
        let extension = &self.tag[start + 3..end];
        let mut subtags = extension.split('-').peekable();
        while let Some(subtag) = subtags.next() {
            if subtag.len() != 2 {
                continue;
            }
            let value_start = subtag.as_ptr() as usize + 2 - self.tag.as_ptr() as usize;
            let mut value_end = value_start;
            while let Some(value) = subtags.next_if(|value| value.len() > 2) {
                value_end = value.as_ptr() as usize + value.len() - self.tag.as_ptr() as usize;
            }
            if subtag == key {
                return Some(if value_end == value_start {
                    ""
                } else {
                    &self.tag[value_start + 1..value_end]
                });
            }
        }
        None
    }

    /// The identifier with its Unicode extension sequence removed, as
    /// LookupMatchingLocaleByPrefix step 1.a requires.
    fn without_unicode_extension(&self) -> String {
        match self.unicode_extension {
            Some((start, end)) => format!("{}{}", &self.tag[..start], &self.tag[end..]),
            None => self.tag.to_owned(),
        }
    }
}

/// LookupMatchingLocaleByPrefix (ECMA-402 9.2.2) against one sorted table.
fn lookup_matching_prefix<T: Copy>(table: &[(&str, T)], locale: &str) -> Option<T> {
    let mut prefix = locale;
    loop {
        if let Some(value) = table_lookup(table, prefix) {
            return Some(value);
        }
        let mut position = prefix.rfind('-')?;
        if position >= 2 && prefix.as_bytes()[position - 2] == b'-' {
            position -= 2;
        }
        prefix = &prefix[..position];
    }
}

struct RegionPreference {
    region: String,
    region_override: Option<String>,
}

impl RegionPreference {
    /// `preferredRegions` of CalendarsOfLocale and HourCyclesOfLocale.
    fn preferred_regions(&self) -> impl Iterator<Item = &str> {
        self.region_override
            .as_deref()
            .into_iter()
            .chain(core::iter::once(self.region.as_str()))
    }
}

/// Borrowed pinned data needed to answer one query.
pub(super) struct LocaleInformation<'p> {
    pub(super) canonicalizer: &'p LocaleCanonicalizer,
    pub(super) expander: &'p LocaleExpander,
    pub(super) rules: &'p ReservedLanguageAliasRules,
    pub(super) numbers: &'p NumberProfiles,
    pub(super) named_time_zones: &'p NamedTimeZones,
}

fn identifiers<'s>(values: impl IntoIterator<Item = &'s str>) -> LocaleInfoResult {
    LocaleInfoResult::Identifiers(values.into_iter().map(Box::from).collect())
}

impl LocaleInformation<'_> {
    pub(super) fn locale_info(
        &self,
        request: LocaleInfoRequest,
    ) -> Result<LocaleInfoResult, LocaleInfoError> {
        let view = LocaleView::parse(request.locale().as_str())?;
        match request.query() {
            LocaleInfoQuery::Calendars => self.calendars(&view, request.locale()),
            LocaleInfoQuery::Collations => Ok(Self::collations(&view)),
            LocaleInfoQuery::HourCycles => self.hour_cycles(&view, request.locale()),
            LocaleInfoQuery::NumberingSystems => Ok(self.numbering_systems(&view)),
            LocaleInfoQuery::TimeZones => Ok(Self::time_zones(&view)),
            LocaleInfoQuery::TextDirection => self.text_direction(&view, request.locale()),
            LocaleInfoQuery::WeekInfo => self.week_info(&view, request.locale()),
        }
    }

    /// Add Likely Subtags followed by CanonicalizeUnicodeLocaleId. `None`
    /// reports the algorithm's signaled error.
    fn maximize(
        &self,
        locale: &CanonicalLocaleId,
    ) -> Result<Option<CanonicalLocaleId>, LocaleInfoError> {
        let input = LocaleId::parse(locale.as_str()).map_err(|_| {
            LocaleInfoError::InvalidLocale("canonical tag is not structurally valid")
        })?;
        let parsed = match ParsedLocale::parse(&input) {
            Ok(parsed) => parsed,
            Err(_) => return Ok(None),
        };
        match parsed.apply_likely_subtags(
            LikelySubtags::Maximize,
            self.expander,
            self.canonicalizer,
            self.rules,
        ) {
            Ok(maximal) => Ok(Some(maximal)),
            Err(LocaleTransformError::Unsupported(_)) => Ok(None),
            Err(LocaleTransformError::InvalidProviderResult(_)) => Err(
                LocaleInfoError::InvalidData("likely subtags produced a non-canonical tag"),
            ),
        }
    }

    /// CanonicalUnicodeSubdivision (15.5.7).
    fn canonical_subdivision(
        &self,
        value: Option<&str>,
    ) -> Result<Option<String>, LocaleInfoError> {
        let Some(value) = value else {
            return Ok(None);
        };
        let bytes = value.as_bytes();
        let region_length = if bytes.len() >= 3 && bytes[..3].iter().all(u8::is_ascii_digit) {
            3
        } else if bytes.len() >= 2 && bytes[..2].iter().all(u8::is_ascii_alphabetic) {
            2
        } else {
            return Ok(None);
        };
        let suffix = &bytes[region_length..];
        if !(1..=4).contains(&suffix.len()) || !suffix.iter().all(u8::is_ascii_alphanumeric) {
            return Ok(None);
        }
        let region_locale = LocaleId::parse(format!("und-{}", &value[..region_length]))
            .map_err(|_| LocaleInfoError::InvalidLocale("subdivision region"))?;
        let canonical = ParsedLocale::parse(&region_locale)
            .map_err(|_| LocaleInfoError::InvalidData("subdivision region is not parseable"))?
            .canonicalize(self.canonicalizer, self.rules)
            .map_err(|_| LocaleInfoError::InvalidData("subdivision region canonicalization"))?;
        Ok(LocaleView::parse(canonical.as_str())?
            .region
            .map(str::to_owned))
    }

    /// RegionPreference (15.5.8).
    fn region_preference(
        &self,
        view: &LocaleView<'_>,
        locale: &CanonicalLocaleId,
    ) -> Result<RegionPreference, LocaleInfoError> {
        let region = match view.region {
            Some(region) => region.to_owned(),
            None => match self.canonical_subdivision(view.keyword("sd"))? {
                Some(region) => region,
                None => {
                    let maximal = self.maximize(locale)?.unwrap_or_else(|| locale.clone());
                    LocaleView::parse(maximal.as_str())?
                        .region
                        .unwrap_or(WORLD)
                        .to_owned()
                }
            },
        };
        let region_override = self.canonical_subdivision(view.keyword("rg"))?;
        Ok(RegionPreference {
            region,
            region_override,
        })
    }

    /// CalendarsOfLocale (15.5.9). CLDR47 calendar preferences are keyed by
    /// region only; the generator rejects a language-region row.
    fn calendars(
        &self,
        view: &LocaleView<'_>,
        locale: &CanonicalLocaleId,
    ) -> Result<LocaleInfoResult, LocaleInfoError> {
        if let Some(calendar) = view.keyword("ca") {
            return Ok(identifiers([calendar]));
        }
        let preference = self.region_preference(view, locale)?;
        let in_use = preference
            .preferred_regions()
            .find_map(|region| table_lookup(generated::CALENDAR_PREFERENCES, region))
            .unwrap_or(&[]);
        let mut list: Vec<&str> = Vec::new();
        for &calendar in in_use {
            // AvailableCalendars: the calendars Intl.DateTimeFormat formats.
            if DateTimeCalendar::parse(calendar).is_some() && !list.contains(&calendar) {
                list.push(calendar);
            }
        }
        if list.is_empty() {
            list.push(DEFAULT_CALENDAR);
        }
        Ok(identifiers(list))
    }

    /// CollationsOfLocale (15.5.10).
    fn collations(view: &LocaleView<'_>) -> LocaleInfoResult {
        if let Some(collation) = view.keyword("co") {
            return identifiers([collation]);
        }
        let list = lookup_matching_prefix(
            generated::COLLATOR_LOCALES,
            &view.without_unicode_extension(),
        )
        .map_or(UNMATCHED_COLLATIONS, |set| generated::COLLATION_SETS[set]);
        identifiers(list.iter().copied())
    }

    /// HourCyclesOfLocale (15.5.11).
    fn hour_cycles(
        &self,
        view: &LocaleView<'_>,
        locale: &CanonicalLocaleId,
    ) -> Result<LocaleInfoResult, LocaleInfoError> {
        if let Some(cycle) = view.keyword("hc") {
            return Ok(identifiers([cycle]));
        }
        let preference = self.region_preference(view, locale)?;
        let cycles = preference
            .preferred_regions()
            .find_map(|region| {
                table_lookup(
                    generated::HOUR_CYCLES,
                    &format!("{}-{region}", view.language),
                )
                .or_else(|| table_lookup(generated::HOUR_CYCLES, region))
            })
            .unwrap_or(&[DEFAULT_HOUR_CYCLE]);
        Ok(identifiers(cycles.iter().map(|cycle| cycle.as_str())))
    }

    /// NumberingSystemsOfLocale (15.5.12).
    fn numbering_systems(&self, view: &LocaleView<'_>) -> LocaleInfoResult {
        if let Some(system) = view.keyword("nu") {
            return identifiers([system]);
        }
        let system =
            default_numbering_system_by_prefix(&view.without_unicode_extension(), self.numbers)
                .unwrap_or(UNMATCHED_NUMBERING_SYSTEM);
        identifiers([system])
    }

    /// TimeZonesOfLocale (15.5.13): IANA zone.tab zones of the region.
    fn time_zones(view: &LocaleView<'_>) -> LocaleInfoResult {
        let Some(region) = view.region else {
            return LocaleInfoResult::Undefined;
        };
        identifiers(
            table_lookup(generated::REGION_TIME_ZONES, region)
                .unwrap_or(&[])
                .iter()
                .copied(),
        )
    }

    /// TextDirectionOfLocale (15.5.14).
    fn text_direction(
        &self,
        view: &LocaleView<'_>,
        locale: &CanonicalLocaleId,
    ) -> Result<LocaleInfoResult, LocaleInfoError> {
        let script = match view.script {
            Some(script) => Some(script.to_owned()),
            None => match self.maximize(locale)? {
                Some(maximal) => LocaleView::parse(maximal.as_str())?
                    .script
                    .map(str::to_owned),
                None => None,
            },
        };
        Ok(script
            .and_then(|script| table_lookup(generated::SCRIPT_DIRECTIONS, &script))
            .map_or(LocaleInfoResult::Undefined, LocaleInfoResult::Direction))
    }

    /// WeekInfoOfLocale (15.5.17).
    fn week_info(
        &self,
        view: &LocaleView<'_>,
        locale: &CanonicalLocaleId,
    ) -> Result<LocaleInfoResult, LocaleInfoError> {
        let preference = self.region_preference(view, locale)?;
        let row = preference
            .region_override
            .as_deref()
            .and_then(|region| table_lookup(generated::WEEK_DATA, region))
            .or_else(|| table_lookup(generated::WEEK_DATA, &preference.region))
            .or_else(|| table_lookup(generated::WEEK_DATA, WORLD))
            .ok_or(LocaleInfoError::InvalidData("week data lacks the 001 row"))?;
        let first_day = view
            .keyword("fw")
            .and_then(IsoWeekday::from_first_day_value)
            .unwrap_or(row.first_day);
        let week = WeekInfo::new(first_day, row.weekend.into())
            .map_err(|_| LocaleInfoError::InvalidData("generated weekend is not ascending"))?;
        Ok(LocaleInfoResult::Week(week))
    }

    /// Intl.supportedValuesOf (8.3.2) lists, each sorted in code unit order.
    pub(super) fn supported_values(
        &self,
        key: SupportedValuesKey,
    ) -> Result<SupportedValuesResult, LocaleInfoError> {
        let mut values: Vec<Box<str>> = match key {
            SupportedValuesKey::Calendar => DateTimeCalendar::ALL
                .iter()
                .map(|calendar| Box::from(calendar.as_str()))
                .collect(),
            SupportedValuesKey::Collation => generated::AVAILABLE_COLLATIONS
                .iter()
                .map(|&collation| Box::from(collation))
                .collect(),
            SupportedValuesKey::Currency => self
                .numbers
                .labeled_currency_codes()
                .into_iter()
                .map(|code| {
                    core::str::from_utf8(&code)
                        .map(Box::from)
                        .map_err(|_| LocaleInfoError::InvalidData("currency code is not ASCII"))
                })
                .collect::<Result<_, _>>()?,
            SupportedValuesKey::NumberingSystem => self
                .numbers
                .numbering_systems()
                .iter()
                .map(|&system| Box::from(system))
                .collect(),
            SupportedValuesKey::TimeZone => self
                .named_time_zones
                .primary_identifiers()
                .into_iter()
                .map(Box::from)
                .collect(),
            SupportedValuesKey::Unit => SingleUnit::ALL
                .iter()
                .map(|unit| Box::from(unit.name()))
                .collect(),
        };
        values.sort_unstable();
        values.dedup();
        SupportedValuesResult::new(values.into_boxed_slice())
            .map_err(|_| LocaleInfoError::InvalidData("supported values are not sortable"))
    }
}

#[cfg(test)]
mod tests;
