//! The ordered registry of shared runtime-helper functions.
//!
//! One row owns each helper's registration order, exact typed operands and
//! results. Named caller/body projections derive from that row; no shared
//! JavaScript-call signature or semantic byte address crosses a helper call.

use lila_ir::ToPrimitiveHint;

use crate::code_sink::Function;
use crate::gc_types::*;
use crate::module::StaticSignature;
use crate::RuntimeErrorMessage;
use wasm_encoder::Instruction;

/// Maximum bytes for one RegExp matcher's transient choice-frame arena.
///
/// The caller capture output, live capture/repeat state and all retained choice
/// frames share this ceiling. A single checked tail owner starts with one frame
/// and grows capacity only for actual backtracking demand after immutable input
/// materialization. Numeric repetition bounds never size an allocation. Admission
/// and failed memory growth report ResourceExhausted (RangeError) before writes;
/// the arena is scrubbed and rewound before an observable matcher exit.
pub(crate) const REGEXP_MATCHER_SCRATCH_MAX_BYTES: i64 = 512 * 1024 * 1024;

/// How a failed RegExp matcher result becomes a JavaScript throw.
///
/// Corrupt generated bytecode is an internal engine failure and preserves the
/// existing generic `Error`. Exhausting the explicitly allocated matcher arena
/// is a resource failure and therefore uses the current function realm's
/// `RangeError`. Keeping this as a closed domain makes a third route an
/// exhaustive-match update at the sole consumer rather than a boolean policy.
pub(crate) enum RegExpMatcherFailureRoute {
    GenericError,
    CurrentFunctionRealmRangeError,
}

/// Declares the complete RegExp matcher status ABI from one failure-row source.
///
/// Each row must choose its wire word, JavaScript error route and stable
/// message. The macro derives both `ALL` views and every projection, so adding
/// a failure cannot leave the helper writer, dynamic result router or string
/// pool on an old parallel list.
macro_rules! regexp_matcher_status_domain {
    (
        $(
            $failure:ident => {
                word: $word:literal,
                route: $route:ident,
                message: $message:ident,
            }
        ),+ $(,)?
    ) => {
        #[derive(Debug, Clone, Copy, PartialEq, Eq)]
        pub(crate) enum RegExpMatcherFailure {
            $( $failure, )+
        }

        impl RegExpMatcherFailure {
            pub(crate) const ALL: &'static [Self] = &[
                $( Self::$failure, )+
            ];

            pub(crate) const fn abi_word(self) -> i64 {
                match self {
                    $( Self::$failure => $word, )+
                }
            }

            pub(crate) const fn route(self) -> RegExpMatcherFailureRoute {
                match self {
                    $( Self::$failure => RegExpMatcherFailureRoute::$route, )+
                }
            }

            pub(crate) const fn message(self) -> RuntimeErrorMessage {
                match self {
                    $( Self::$failure => RuntimeErrorMessage::$message, )+
                }
            }
        }

        /// The four-result matcher's final result slot.
        ///
        /// `Complete` covers both match and no-match; the first result slot
        /// distinguishes those normal outcomes. Every failure retains its
        /// typed reason until the observable wrapper has rewound transient
        /// scratch storage and is ready to throw.
        #[derive(Debug, Clone, Copy, PartialEq, Eq)]
        pub(crate) enum RegExpMatcherStatus {
            Complete,
            Failed(RegExpMatcherFailure),
        }

        impl RegExpMatcherStatus {
            pub(crate) const ALL: &'static [Self] = &[
                Self::Complete,
                $( Self::Failed(RegExpMatcherFailure::$failure), )+
            ];

            pub(crate) const fn abi_word(self) -> i64 {
                match self {
                    Self::Complete => 0,
                    Self::Failed(failure) => failure.abi_word(),
                }
            }
        }
    };
}

regexp_matcher_status_domain! {
    CorruptProgram => {
        word: 1,
        route: GenericError,
        message: REGEXP_COMPILED_PROGRAM_MATCHER_FAILED,
    },
    ResourceExhausted => {
        word: 2,
        route: CurrentFunctionRealmRangeError,
        message: REGEXP_MATCHER_SCRATCH_ARENA_EXCEEDS_THE_ENGINE_ADDRESSABLE_RESOURCE_LIMIT,
    },
}

const fn regexp_matcher_status_words_are_unique() -> bool {
    let mut left = 0;
    while left < RegExpMatcherStatus::ALL.len() {
        let mut right = left + 1;
        while right < RegExpMatcherStatus::ALL.len() {
            if RegExpMatcherStatus::ALL[left].abi_word()
                == RegExpMatcherStatus::ALL[right].abi_word()
            {
                return false;
            }
            right += 1;
        }
        left += 1;
    }
    true
}

const _: () = assert!(
    regexp_matcher_status_words_are_unique(),
    "RegExp matcher statuses must have unique ABI words"
);

/// The pure Pattern compiler's private second result slot. These are not
/// JavaScript completion tags. Syntax/resource/internal failures retain
/// JavaScript errors.
/// No non-success result publishes receiver state.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum RegExpCompilerStatus {
    Compiled,
    SyntaxError,
    ResourceExhausted,
    CorruptProgram,
}
impl RegExpCompilerStatus {
    pub(crate) const ALL: [Self; 4] = [
        Self::Compiled,
        Self::SyntaxError,
        Self::ResourceExhausted,
        Self::CorruptProgram,
    ];
    pub(crate) const fn abi_word(self) -> i64 {
        match self {
            Self::Compiled => 0,
            Self::SyntaxError => 1,
            Self::ResourceExhausted => 3,
            Self::CorruptProgram => 4,
        }
    }
}

/// One fact a module can carry about itself that some *conditional* runtime
/// helper's emission depends on.
///
/// Closed set, and the only way to put a fact into a [`RuntimeHelperEmission`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub(crate) enum RuntimeHelperFact {
    UsesJsonStringify = 0,
}

impl RuntimeHelperFact {
    const fn bit(self) -> u32 {
        1u32 << (self as u32)
    }
}

/// The facts a module knows about itself that decide whether a *conditional*
/// runtime helper is emitted at all.
///
/// Passed by value into [`RuntimeHelperId::is_emitted`] so that the emission
/// condition of every helper is stated in exactly one place, next to its type
/// index, rather than being spread over an `if` in the function section and a
/// matching `if let Some(..)` in the code section.
///
/// A *set* of [`RuntimeHelperFact`]s rather than a struct of `bool` fields,
/// because [`Self::NONE`] has to mean "no fact holds" by construction. As a
/// struct literal it was a hand-written list that whoever added the second
/// conditional helper would also have had to remember to extend with `false`;
/// writing `true` there instead compiles, makes [`RuntimeHelperId::is_conditional`]
/// answer `false` for a genuinely conditional helper, and silently defeats
/// [`RuntimeHelperId::conditional_helpers_are_last`] — handing out shifted
/// function indices with both `const` assertions still green. The empty set
/// cannot be written wrong.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct RuntimeHelperEmission(u32);

impl RuntimeHelperEmission {
    /// The emission context in which every conditional helper is absent. Used
    /// by [`RuntimeHelperId::is_conditional`] so "conditional" is derived from
    /// `is_emitted` instead of being a second, separately-maintained match.
    pub(crate) const NONE: Self = Self(0);

    /// Adds `fact` to the set when `holds`. The only constructor beyond
    /// [`Self::NONE`], so every emission context is built up from the empty one.
    pub(crate) const fn with(self, fact: RuntimeHelperFact, holds: bool) -> Self {
        if holds {
            Self(self.0 | fact.bit())
        } else {
            self
        }
    }

    pub(crate) const fn holds(self, fact: RuntimeHelperFact) -> bool {
        self.0 & fact.bit() != 0
    }
}

/// A checked Key parameter is minted only by a registered Key row. It cannot
/// be made from an arbitrary value by object-family callers.
pub(crate) struct RuntimeHelperPropertyKeyParameter {
    value: ValueLocals,
}
impl RuntimeHelperPropertyKeyParameter {
    pub(crate) fn into_value(self) -> ValueLocals {
        self.value
    }
}

/// Presence is separate from the value tag: Read(undefined) still performs
/// the prescribed option validation, while an omitted options read does not.
/// Only the registered OptionalValue operand can construct this parameter.
pub(crate) struct RuntimeHelperOptionalValueParameter {
    present: I32Local,
    value: ValueLocals,
}
impl RuntimeHelperOptionalValueParameter {
    fn emit_argument(value: Option<&ValueLocals>, function: &mut Function) {
        match value {
            Some(value) => {
                function.instruction(&Instruction::I32Const(1));
                value.emit(function);
            }
            None => {
                function.instruction(&Instruction::I32Const(0));
                function.instruction(&Instruction::I32Const(
                    crate::WasmRuntimeValueTag::Undefined as i32,
                ));
                function.instruction(&Instruction::I64Const(0));
                function.instruction(&Instruction::RefNull(wasm_encoder::HeapType::Abstract {
                    shared: false,
                    ty: wasm_encoder::AbstractHeapType::Eq,
                }));
            }
        }
    }

    pub(crate) fn emit_if_present(
        &self,
        builder: &mut crate::emit::FunctionBuilder<'_>,
        function: &mut Function,
        consume: impl FnOnce(
            &ValueLocals,
            &mut crate::emit::FunctionBuilder<'_>,
            &mut Function,
        ) -> Result<(), crate::EmitError>,
    ) -> Result<(), crate::EmitError> {
        self.present.load(function);
        builder.open_frame(crate::emit::ControlFrameKind::If, function);
        consume(&self.value, builder, function)?;
        builder.pop_control(crate::emit::ControlFrameKind::If);
        function.instruction(&Instruction::End);
        Ok(())
    }

    fn release(self, function: &mut Function) {
        self.value.clear(function);
    }
}

mod helper_sealed {
    pub trait Arguments {}
    pub trait Parameters {}
}

/// Which half of the module a helper body belongs to.
///
/// A runtime body is identical for every program and sits below `main`. A
/// program body is generated from the script and sits after the program's own
/// callables, so it can never shift a runtime index.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum HelperOwner {
    /// Program-independent; reached by plain `call`.
    Runtime,
    /// Program-generated; reached by plain `call` from program code only.
    Program,
    /// Program-generated and reached from runtime code through its hook global
    /// (null until `main` installs it), see [`RuntimeSchema::call_hook`].
    Hook(ProgramHook),
}

/// Every place runtime code asks the program a question only the program can
/// answer. Each hook is one mutable global typed by its helper row.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub(crate) enum ProgramHook {
    /// `new Function(...)` and its generator/async siblings.
    PreparedDynamicFunction,
    /// Indirect eval, `$262.evalScript` and `ShadowRealm.prototype.evaluate`.
    PreparedScript,
    /// `ShadowRealm.prototype.importValue`.
    RealmModuleImport,
    /// The promise job that resumes a module body.
    ModuleBodyReaction,
    /// RegExp construction from a source/flags pair the program spelled out.
    RegExpProgramCandidate,
}

impl ProgramHook {
    pub(crate) const ALL: [Self; 5] = [
        Self::PreparedDynamicFunction,
        Self::PreparedScript,
        Self::RealmModuleImport,
        Self::ModuleBodyReaction,
        Self::RegExpProgramCandidate,
    ];
    pub(crate) const fn helper(self) -> RuntimeHelperId {
        match self {
            Self::PreparedDynamicFunction => RuntimeHelperId::PreparedDynamicFunction,
            Self::PreparedScript => RuntimeHelperId::PreparedScript,
            Self::RealmModuleImport => RuntimeHelperId::RealmModuleImport,
            Self::ModuleBodyReaction => RuntimeHelperId::ModuleBodyReaction,
            Self::RegExpProgramCandidate => RuntimeHelperId::RegExpProgramCandidate,
        }
    }
}

impl HelperOwner {
    const fn region(self) -> HelperRegion {
        match self {
            Self::Runtime => HelperRegion::Runtime,
            Self::Program | Self::Hook(_) => HelperRegion::Program,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum HelperRegion {
    Runtime,
    Program,
}

/// The first index of each helper region. Only `FunctionIndexLayout` mints it
/// and only this owner performs helper-index arithmetic; callers retain the plan.
#[derive(Debug, Clone, Copy)]
pub(crate) struct RuntimeHelperFunctionBase {
    runtime_first: u32,
    program_first: u32,
}
impl RuntimeHelperFunctionBase {
    pub(crate) const fn at(runtime_first: u32, program_first: u32) -> Self {
        Self {
            runtime_first,
            program_first,
        }
    }
}

/// How a call reaches its helper body.
pub(crate) enum HelperRoute {
    Direct(RuntimeHelperFunctionBase),
    Hook,
}

/// Proof that the generated code tested a hook global for null on the path
/// that holds this value. Minted only by
/// `FunctionBuilder::emit_program_hook_dispatch`.
pub(crate) struct InstalledHook {
    hook: ProgramHook,
}
impl InstalledHook {
    pub(crate) const fn mint(hook: ProgramHook) -> Self {
        Self { hook }
    }
}

pub(crate) trait HelperArguments: helper_sealed::Arguments {
    type Result;
    const ID: RuntimeHelperId;
    fn emit_call(
        self,
        schema: &RuntimeSchema,
        route: HelperRoute,
        function: &mut Function,
    ) -> Self::Result;
}
pub(crate) trait HelperParameters: helper_sealed::Parameters + Sized {
    const ID: RuntimeHelperId;
    fn acquire(schema: &RuntimeSchema, function: &mut Function) -> Self;
    fn release(self, function: &mut Function);
    fn caller_environment(&self) -> Option<&GcLocal<Environment, Nullable>>;
    fn caller_function_context(&self) -> Option<&GcLocal<FunctionContext>>;
    fn caller_execution_realm(&self) -> Option<&GcLocal<RealmRecord>>;
}

pub(crate) struct HelperCompletion {
    private: (),
}
impl HelperCompletion {
    pub(crate) fn store(self, destination: &CompletionLocals, function: &mut Function) {
        destination
            .value()
            .store_call_result(destination.kind(), destination.target(), function);
    }
}
pub(crate) struct I32HelperResult {
    private: (),
}
impl I32HelperResult {
    pub(crate) fn store(self, destination: I32Local, function: &mut Function) {
        destination.store(function);
    }
}
pub(crate) struct I64HelperResult {
    private: (),
}
impl I64HelperResult {
    pub(crate) fn store(self, destination: I64Local, function: &mut Function) {
        destination.store(function);
    }
}
/// Only the calendar year owner can project this complete seven-word result.
#[must_use = "the completed year must initialize its owned calendar record"]
pub(crate) struct EastAsianYearCallResult {
    private: (),
}
#[must_use = "the selected Umm al-Qura year and packed row must be consumed together"]
pub(crate) struct UmmAlQuraYearCallResult {
    private: (),
}
#[must_use = "the complete projection must initialize its owned calendar date"]
pub(crate) struct CalendarDateCallResult {
    private: (),
}
#[must_use = "all three completed ISO fields must be consumed together"]
pub(crate) struct CalendarIsoDateCallResult {
    private: (),
}
#[must_use = "the balanced calendar year and month must be consumed together"]
pub(crate) struct CalendarYearMonthCallResult {
    private: (),
}
#[must_use = "the calendar difference must retain all four date duration fields"]
pub(crate) struct CalendarDifferenceCallResult {
    private: (),
}
pub(crate) struct ReferenceHelperResult<T: GcHeapType, N: GcFieldNullability> {
    private: std::marker::PhantomData<fn() -> (T, N)>,
}
impl<T: GcHeapType, N: GcFieldNullability> ReferenceHelperResult<T, N> {
    pub(crate) fn bind(
        self,
        schema: &RuntimeSchema,
        slot: GcLocalSlot<T, N>,
        function: &mut Function,
    ) -> GcLocal<T, N> {
        schema.bind_helper_reference(self, slot, function)
    }
}
pub(crate) struct RegExpMatchCallResult {
    private: (),
}
impl RegExpMatchCallResult {
    pub(crate) fn store(
        self,
        found: I32Local,
        start: I64Local,
        end: I64Local,
        status: I32Local,
        function: &mut Function,
    ) {
        status.store(function);
        end.store(function);
        start.store(function);
        found.store(function);
    }
}
pub(crate) struct RegExpCompileCallResult {
    private: (),
}
impl RegExpCompileCallResult {
    pub(crate) fn bind(
        self,
        schema: &RuntimeSchema,
        program: GcLocalSlot<RegExpProgram, Nullable>,
        status: I32Local,
        cursor: I64Local,
        detail: I64Local,
        function: &mut Function,
    ) -> GcLocal<RegExpProgram, Nullable> {
        detail.store(function);
        cursor.store(function);
        status.store(function);
        schema.bind_regexp_compiler_program(self, program, function)
    }
}
/// A completion followed by one status word. The producer and consumer of each
/// row own what the status means.
#[must_use = "the completion and its status must be consumed together"]
pub(crate) struct StatusCompletionCallResult {
    private: (),
}
impl StatusCompletionCallResult {
    pub(crate) fn store(
        self,
        completion: &CompletionLocals,
        status: I32Local,
        function: &mut Function,
    ) {
        status.store(function);
        completion
            .value()
            .store_call_result(completion.kind(), completion.target(), function);
    }
}
/// The evaluation completion of a Realm module import and its namespace value.
#[must_use = "the evaluation and namespace must be consumed together"]
pub(crate) struct RealmImportCallResult {
    private: (),
}
impl RealmImportCallResult {
    pub(crate) fn store(
        self,
        evaluation: &CompletionLocals,
        namespace: &ValueLocals,
        function: &mut Function,
    ) {
        namespace.store_value_result(function);
        evaluation
            .value()
            .store_call_result(evaluation.kind(), evaluation.target(), function);
    }
}
pub(crate) struct ModuleGatherCallResult {
    private: (),
}
impl ModuleGatherCallResult {
    pub(crate) fn bind(
        self,
        schema: &RuntimeSchema,
        modules: GcLocalSlot<ModuleRegistry>,
        count: I64Local,
        function: &mut Function,
    ) -> GcLocal<ModuleRegistry> {
        count.store(function);
        schema.bind_gathered_modules(self, modules, function)
    }
}

/// Reflect, Math, JSON, Atomics, Temporal and Intl remain rooted across the
/// initialization/publication boundary. An absent namespace has a null result.
#[must_use = "all six Realm namespace results must be rooted before publication"]
pub(crate) struct RealmInitializeIntrinsicsCallResult {
    private: (),
}
impl RealmInitializeIntrinsicsCallResult {
    pub(crate) fn bind(
        self,
        schema: &RuntimeSchema,
        function: &mut Function,
    ) -> [GcLocal<OrdinaryObject, Nullable>; 6] {
        // Bind every stack result before the caller can allocate. Results are
        // popped in reverse ABI order, then returned in publication order.
        let mut roots: [GcLocal<OrdinaryObject, Nullable>; 6] = std::array::from_fn(|_| {
            let slot = schema.reserve_gc_local(function);
            ReferenceHelperResult {
                private: std::marker::PhantomData,
            }
            .bind(schema, slot, function)
        });
        roots.reverse();
        roots
    }
}

macro_rules! helper_field {
    (@realm $self:ident;) => { None };
    (@realm $self:ident; caller_execution_realm:(Ref RealmRecord NonNullable) $(,$rest:ident:$shape:tt)*) => { Some(&$self.caller_execution_realm) };
    (@realm $self:ident; $field:ident:$shape:tt $(,$rest:ident:$rest_shape:tt)*) => {
        helper_field!(@realm $self; $($rest:$rest_shape),*)
    };
    (@context $self:ident;) => { None };
    (@context $self:ident; caller_function_context:(Ref FunctionContext NonNullable) $(,$rest:ident:$shape:tt)*) => { Some(&$self.caller_function_context) };
    (@context $self:ident; $field:ident:$shape:tt $(,$rest:ident:$rest_shape:tt)*) => {
        helper_field!(@context $self; $($rest:$rest_shape),*)
    };
    (@caller $self:ident;) => { None };
    (@caller $self:ident; caller_environment:(Ref Environment Nullable) $(,$rest:ident:$shape:tt)*) => { Some(&$self.caller_environment) };
    (@caller $self:ident; $field:ident:$shape:tt $(,$rest:ident:$rest_shape:tt)*) => {
        helper_field!(@caller $self; $($rest:$rest_shape),*)
    };

    (@argument Value) => { &'a ValueLocals };
    (@argument OptionalValue) => { Option<&'a ValueLocals> };
    (@argument Completion) => { &'a CompletionLocals };
    (@argument Key) => { &'a crate::operations::PropertyKeyLocals };
    (@argument I32) => { I32Local };
    (@argument I64) => { I64Local };
    (@argument (Ref $ty:ident $null:ident)) => { &'a GcLocal<$ty, $null> };
    (@parameter Value) => { ValueLocals };
    (@parameter OptionalValue) => { RuntimeHelperOptionalValueParameter };
    (@parameter Completion) => { CompletionLocals };
    (@parameter Key) => { crate::operations::PropertyKeyLocals };
    (@parameter I32) => { I32Local };
    (@parameter I64) => { I64Local };
    (@parameter (Ref $ty:ident $null:ident)) => { GcLocal<$ty, $null> };
    (@abi Value) => { &[AbiType::I32, AbiType::I64, AbiType::EqRef] };
    (@abi OptionalValue) => { &[AbiType::I32, AbiType::I32, AbiType::I64, AbiType::EqRef] };
    (@abi Completion) => { &crate::module::COMPLETION_TYPES };
    (@abi Key) => { helper_field!(@abi Value) };
    (@abi I32) => { &[AbiType::I32] };
    (@abi I64) => { &[AbiType::I64] };
    (@abi (Ref $ty:ident $null:ident)) => { &[AbiType::Gc(GcLayout::$ty, GcNullability::$null)] };
    (@emit $value:expr, $schema:ident, $function:ident, Value) => { $value.emit($function) };
    (@emit $value:expr, $schema:ident, $function:ident, OptionalValue) => { RuntimeHelperOptionalValueParameter::emit_argument($value, $function) };
    (@emit $value:expr, $schema:ident, $function:ident, Completion) => { $value.emit($function) };
    (@emit $value:expr, $schema:ident, $function:ident, Key) => { $value.value().emit($function) };
    (@emit $value:expr, $schema:ident, $function:ident, I32) => { $value.load($function) };
    (@emit $value:expr, $schema:ident, $function:ident, I64) => { $value.load($function) };
    (@emit $value:expr, $schema:ident, $function:ident, (Ref $ty:ident $null:ident)) => { { $value.load($schema, $function); } };
    (@acquire $schema:ident, $index:ident, $function:ident, Value) => { $schema.parameter_value($index, $function) };
    (@acquire $schema:ident, $index:ident, $function:ident, OptionalValue) => {
        RuntimeHelperOptionalValueParameter {
            present: $schema.parameter_i32($index, $function),
            value: $schema.parameter_value($index + 1, $function),
        }
    };
    (@acquire $schema:ident, $index:ident, $function:ident, Completion) => { $schema.parameter_completion($index, $function) };
    (@acquire $schema:ident, $index:ident, $function:ident, Key) => {
        crate::operations::PropertyKeyLocals::from_helper_parameter(RuntimeHelperPropertyKeyParameter {
            value: $schema.parameter_value($index, $function),
        })
    };
    (@acquire $schema:ident, $index:ident, $function:ident, I32) => { $schema.parameter_i32($index, $function) };
    (@acquire $schema:ident, $index:ident, $function:ident, I64) => { $schema.parameter_i64($index, $function) };
    (@acquire $schema:ident, $index:ident, $function:ident, (Ref $ty:ident $null:ident)) => { $schema.parameter_gc::<$ty, $null>($index, $function) };
    (@release $value:expr, $function:ident, Value) => { $value.clear($function) };
    (@release $value:expr, $function:ident, OptionalValue) => { $value.release($function) };
    (@release $value:expr, $function:ident, Completion) => { $value.clear($function) };
    (@release $value:expr, $function:ident, Key) => { $value.clear($function) };
    (@release $value:expr, $function:ident, I32) => { { let _ = $value; } };
    (@release $value:expr, $function:ident, I64) => { { let _ = $value; } };
    (@release $value:expr, $function:ident, (Ref $ty:ident $null:ident)) => { $value.clear($function) };
    (@reverse_release $self:ident, $function:ident;) => {};
    (@reverse_release $self:ident, $function:ident; $field:ident:$shape:tt $(,$rest:ident:$rest_shape:tt)*) => {
        helper_field!(@reverse_release $self, $function; $($rest:$rest_shape),*);
        helper_field!(@release $self.$field, $function, $shape);
    };
    (@result_type Completion) => { HelperCompletion };
    (@result_type Void) => { () };
    (@result_type I32) => { I32HelperResult };
    (@result_type I64) => { I64HelperResult };
    (@result_type EastAsianYear) => { EastAsianYearCallResult };
    (@result_type UmmAlQuraYear) => { UmmAlQuraYearCallResult };
    (@result_type CalendarDate) => { CalendarDateCallResult };
    (@result_type CalendarIsoDate) => { CalendarIsoDateCallResult };
    (@result_type CalendarYearMonth) => { CalendarYearMonthCallResult };
    (@result_type CalendarDifference) => { CalendarDifferenceCallResult };
    (@result_type (Ref $ty:ident $null:ident)) => { ReferenceHelperResult<$ty, $null> };
    (@result_type RegExpMatch) => { RegExpMatchCallResult };
    (@result_type RegExpCompile) => { RegExpCompileCallResult };
    (@result_type StatusCompletion) => { StatusCompletionCallResult };
    (@result_type RealmImport) => { RealmImportCallResult };
    (@result_type ModuleGather) => { ModuleGatherCallResult };
    (@result_type RealmInitializeIntrinsics) => { RealmInitializeIntrinsicsCallResult };
    (@result_abi Completion) => { crate::module::COMPLETION_TYPES.to_vec() };
    (@result_abi Void) => { Vec::new() };
    (@result_abi I32) => { vec![AbiType::I32] };
    (@result_abi I64) => { vec![AbiType::I64] };
    (@result_abi EastAsianYear) => { vec![AbiType::I64; 7] };
    (@result_abi UmmAlQuraYear) => { vec![AbiType::I64; 2] };
    (@result_abi CalendarDate) => { vec![AbiType::I64; 8] };
    (@result_abi CalendarIsoDate) => { vec![AbiType::I64; 3] };
    (@result_abi CalendarYearMonth) => { vec![AbiType::I64; 2] };
    (@result_abi CalendarDifference) => { vec![AbiType::I64; 4] };
    (@result_abi (Ref $ty:ident $null:ident)) => { vec![AbiType::Gc(GcLayout::$ty, GcNullability::$null)] };
    (@result_abi RegExpMatch) => { vec![AbiType::I32, AbiType::I64, AbiType::I64, AbiType::I32] };
    (@result_abi RegExpCompile) => { vec![AbiType::Gc(GcLayout::RegExpProgram, GcNullability::Nullable), AbiType::I32, AbiType::I64, AbiType::I64] };
    (@result_abi StatusCompletion) => { { let mut types = crate::module::COMPLETION_TYPES.to_vec(); types.push(AbiType::I32); types } };
    (@result_abi RealmImport) => { { let mut types = crate::module::COMPLETION_TYPES.to_vec(); types.extend([AbiType::I32, AbiType::I64, AbiType::EqRef]); types } };
    (@result_abi ModuleGather) => { vec![AbiType::Gc(GcLayout::ModuleRegistry, GcNullability::NonNullable), AbiType::I64] };
    (@result_abi RealmInitializeIntrinsics) => { vec![AbiType::Gc(GcLayout::OrdinaryObject, GcNullability::Nullable); 6] };
    (@result Completion) => { HelperCompletion { private: () } };
    (@result Void) => { () };
    (@result I32) => { I32HelperResult { private: () } };
    (@result I64) => { I64HelperResult { private: () } };
    (@result EastAsianYear) => { EastAsianYearCallResult { private: () } };
    (@result UmmAlQuraYear) => { UmmAlQuraYearCallResult { private: () } };
    (@result CalendarDate) => { CalendarDateCallResult { private: () } };
    (@result CalendarIsoDate) => { CalendarIsoDateCallResult { private: () } };
    (@result CalendarYearMonth) => { CalendarYearMonthCallResult { private: () } };
    (@result CalendarDifference) => { CalendarDifferenceCallResult { private: () } };
    (@result (Ref $ty:ident $null:ident)) => { ReferenceHelperResult { private: std::marker::PhantomData } };
    (@result RegExpMatch) => { RegExpMatchCallResult { private: () } };
    (@result RegExpCompile) => { RegExpCompileCallResult { private: () } };
    (@result StatusCompletion) => { StatusCompletionCallResult { private: () } };
    (@result RealmImport) => { RealmImportCallResult { private: () } };
    (@result ModuleGather) => { ModuleGatherCallResult { private: () } };
    (@result RealmInitializeIntrinsics) => { RealmInitializeIntrinsicsCallResult { private: () } };
}

/// One row owns helper identity, exact operand projection, result shape and
/// registration order. There is no general seven-word helper signature.
macro_rules! runtime_helper_domain {
    ($( $id:ident / $arguments:ident / $parameters:ident / $debug:literal {
        $( $field:ident : $shape:tt ),* $(,)?
    } => $result:tt; )+) => {
        #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
        #[repr(u32)]
        pub(crate) enum RuntimeHelperId { $( $id, )+ }
        impl RuntimeHelperId {
            pub(crate) const ALL: &'static [Self] = &[ $(Self::$id),+ ];
            pub(crate) const fn index(self, base: RuntimeHelperFunctionBase) -> u32 {
                match self.owner().region() {
                    HelperRegion::Runtime => base.runtime_first + self.rank_in_region(),
                    HelperRegion::Program => base.program_first + self.rank_in_region(),
                }
            }
            /// Position among the helpers of the same region, in registration order.
            const fn rank_in_region(self) -> u32 {
                let region = self.owner().region();
                let mut rank = 0;
                let mut position = 0;
                while position < self as usize {
                    if Self::ALL[position].owner().region() as u32 == region as u32 {
                        rank += 1;
                    }
                    position += 1;
                }
                rank
            }
            pub(crate) const fn type_index(self) -> u32 { StaticSignature::ALL.len() as u32 + self as u32 }
            pub(crate) const fn debug_name(self) -> &'static str { match self { $(Self::$id => $debug),+ } }
            pub(crate) fn parameter_types(self) -> Vec<AbiType> {
                match self { $( Self::$id => {
                    let mut types = Vec::new(); $(types.extend_from_slice(helper_field!(@abi $shape));)* types
                }),+ }
            }
            pub(crate) fn result_types(self) -> Vec<AbiType> {
                match self { $(Self::$id => helper_field!(@result_abi $result)),+ }
            }
            pub(crate) fn definition(self, layouts: &GcLayoutRegistry) -> crate::module::StaticSignatureDefinition {
                crate::module::StaticSignatureDefinition::from_abi(self.parameter_types(), self.result_types(), layouts)
            }
        }
        $(
            pub(crate) struct $arguments<'a> {
                $( pub(crate) $field: helper_field!(@argument $shape), )*
                lifetime: std::marker::PhantomData<&'a ()>,
            }
            impl<'a> $arguments<'a> {
                pub(crate) fn new($( $field: helper_field!(@argument $shape) ),*) -> Self {
                    Self { $( $field, )* lifetime: std::marker::PhantomData }
                }
            }
            impl helper_sealed::Arguments for $arguments<'_> {}
            impl HelperArguments for $arguments<'_> {
                type Result = helper_field!(@result_type $result);
                const ID: RuntimeHelperId = RuntimeHelperId::$id;
                fn emit_call(self, schema: &RuntimeSchema, route: HelperRoute, function: &mut Function) -> Self::Result {
                    $(helper_field!(@emit self.$field, schema, function, $shape);)*
                    Self::ID.emit_invocation(schema, route, function);
                    helper_field!(@result $result)
                }
            }
            pub(crate) struct $parameters { $( pub(crate) $field: helper_field!(@parameter $shape), )* }
            impl helper_sealed::Parameters for $parameters {}
            impl HelperParameters for $parameters {
                const ID: RuntimeHelperId = RuntimeHelperId::$id;
                fn acquire(schema: &RuntimeSchema, function: &mut Function) -> Self {
                    let signature = Self::ID.definition(schema.layouts());
                    assert_eq!(function.parameter_types(), signature.parameters(), "helper parameter owner mismatch");
                    let mut index = 0u32;
                    $(let $field = helper_field!(@acquire schema, index, function, $shape);
                      index += helper_field!(@abi $shape).len() as u32;)*
                    debug_assert_eq!(index as usize, signature.parameters().len());
                    Self { $($field),* }
                }
                fn release(self, function: &mut Function) {
                    helper_field!(@reverse_release self, function; $($field:$shape),*);
                }
                fn caller_environment(&self) -> Option<&GcLocal<Environment, Nullable>> {
                    helper_field!(@caller self; $($field:$shape),*)
                }
                fn caller_function_context(&self) -> Option<&GcLocal<FunctionContext>> {
                    helper_field!(@context self; $($field:$shape),*)
                }
                fn caller_execution_realm(&self) -> Option<&GcLocal<RealmRecord>> {
                    helper_field!(@realm self; $($field:$shape),*)
                }
            }
        )+
    };
}

runtime_helper_domain! {
    TransientByteAlloc / TransientByteAllocArguments / TransientByteAllocParameters / "transient_byte_alloc" { size:I64 } => I64;
    ArrayIndexedPublish / ArrayIndexedPublishArguments / ArrayIndexedPublishParameters / "array_indexed_publish" { storage:(Ref ArrayIndexStorage NonNullable),index:I64,descriptor:(Ref PropertyDescriptor NonNullable) } => Void;
    ArrayIndexedDelete / ArrayIndexedDeleteArguments / ArrayIndexedDeleteParameters / "array_indexed_delete" { storage:(Ref ArrayIndexStorage NonNullable),index:I64 } => Void;
    ObjectRead / ObjectReadArguments / ObjectReadParameters / "object_read" { target:Value,receiver:Value,key:Key,caller_environment:(Ref Environment Nullable) } => Completion;
    ObjectWrite / ObjectWriteArguments / ObjectWriteParameters / "object_write" { target:Value,key:Key,value:Value,strict:I32,caller_environment:(Ref Environment Nullable) } => Completion;
    ObjectDefineData / ObjectDefineDataArguments / ObjectDefineDataParameters / "object_define_data" { target:Value,key:Key,value:Value,writable:I32,enumerable:I32,configurable:I32,caller_environment:(Ref Environment Nullable) } => Completion;
    OrdinaryPropertyAppend / OrdinaryPropertyAppendArguments / OrdinaryPropertyAppendParameters / "ordinary_property_append" { object:(Ref OrdinaryObject NonNullable),key:Key,descriptor:(Ref PropertyDescriptor NonNullable) } => Void;
    ObjectHeaderProjection / ObjectHeaderProjectionArguments / ObjectHeaderProjectionParameters / "object_header_projection" { value:Value } => (Ref OrdinaryObject NonNullable);
    OrdinaryObjectAllocate / OrdinaryObjectAllocateArguments / OrdinaryObjectAllocateParameters / "ordinary_object_allocate" { prototype:Value,immutable_prototype:I32 } => (Ref OrdinaryObject NonNullable);
    ValueToObject / ValueToObjectArguments / ValueToObjectParameters / "value_to_object" { realm:(Ref RealmRecord NonNullable),input:Value } => Completion;
    FunctionMetadataPublish / FunctionMetadataPublishArguments / FunctionMetadataPublishParameters / "function_metadata_publish" { callable:(Ref FunctionObject NonNullable),length_bits:I64,name:(Ref StringValue NonNullable),configurable:I32,has_caller:I32,create_prototype:I32,constructor_back_reference:I32,prototype_parent:Value } => Void;
    RealmInitializeIntrinsics / RealmInitializeIntrinsicsArguments / RealmInitializeIntrinsicsParameters / "realm_initialize_intrinsics" { realm:(Ref RealmRecord NonNullable),caller_environment:(Ref Environment Nullable) } => RealmInitializeIntrinsics;
    ProxyCall / ProxyCallArguments / ProxyCallParameters / "proxy_call" { callee:Value,this_value:Value,arguments:(Ref ValueArray NonNullable),caller_environment:(Ref Environment Nullable) } => Completion;
    ProxyConstruct / ProxyConstructArguments / ProxyConstructParameters / "proxy_construct" { callee:Value,new_target:Value,arguments:(Ref ValueArray NonNullable),caller_environment:(Ref Environment Nullable) } => Completion;
    StringEquality / StringEqualityArguments / StringEqualityParameters / "string_equality" { left:(Ref StringValue NonNullable),right:(Ref StringValue NonNullable),ascii_fold:I32 } => I32;
    NumberToString / NumberToStringArguments / NumberToStringParameters / "number_to_string" { bits:I64 } => (Ref StringValue NonNullable);
    StringToNumber / StringToNumberArguments / StringToNumberParameters / "string_to_number" { input:(Ref StringValue NonNullable) } => I64;
    ValueToString / ValueToStringArguments / ValueToStringParameters / "value_to_string" { input:Value,caller_environment:(Ref Environment Nullable) } => Completion;
    ValueToNumber / ValueToNumberArguments / ValueToNumberParameters / "value_to_number" { input:Value,caller_environment:(Ref Environment Nullable) } => Completion;
    ValueToNumeric / ValueToNumericArguments / ValueToNumericParameters / "value_to_numeric" { input:Value,caller_environment:(Ref Environment Nullable) } => Completion;
    CoerciveAdd / CoerciveAddArguments / CoerciveAddParameters / "coercive_add" { left:Value,right:Value,caller_execution_realm:(Ref RealmRecord NonNullable),caller_environment:(Ref Environment Nullable) } => Completion;
    ObjectGetPrototypeOf / ObjectGetPrototypeOfArguments / ObjectGetPrototypeOfParameters / "object_get_prototype_of" { target:Value,caller_environment:(Ref Environment Nullable) } => Completion;
    ObjectIsExtensible / ObjectIsExtensibleArguments / ObjectIsExtensibleParameters / "object_is_extensible" { target:Value,caller_environment:(Ref Environment Nullable) } => Completion;
    ObjectPreventExtensions / ObjectPreventExtensionsArguments / ObjectPreventExtensionsParameters / "object_prevent_extensions" { target:Value,caller_environment:(Ref Environment Nullable) } => Completion;
    ObjectReadProxy / ObjectReadProxyArguments / ObjectReadProxyParameters / "object_read_proxy" { target:Value,receiver:Value,key:Key,caller_environment:(Ref Environment Nullable) } => Completion;
    RegExpMatcher / RegExpMatcherArguments / RegExpMatcherParameters / "regexp_matcher" { program:(Ref RegExpProgram NonNullable),input:(Ref StringValue NonNullable),start:I64,flags:I32,scratch:I64 } => RegExpMatch;
    FunctionCall / FunctionCallArguments / FunctionCallParameters / "function_call" { callee:Value,this_value:Value,arguments:(Ref ValueArray NonNullable),caller_environment:(Ref Environment Nullable) } => Completion;
    DynamicPropertyRead / DynamicPropertyReadArguments / DynamicPropertyReadParameters / "dynamic_property_read" { target:Value,receiver:Value,key:Value,caller_environment:(Ref Environment Nullable) } => Completion;
    OrdinarySetDataOnReceiver / OrdinarySetDataOnReceiverArguments / OrdinarySetDataOnReceiverParameters / "ordinary_set_data_on_receiver" { receiver:Value,key:Key,value:Value,caller_environment:(Ref Environment Nullable) } => Completion;
    OrdinarySet / OrdinarySetArguments / OrdinarySetParameters / "ordinary_set" { target:Value,receiver:Value,key:Key,value:Value,caller_environment:(Ref Environment Nullable) } => Completion;
    DecimalToBinary64 / DecimalToBinary64Arguments / DecimalToBinary64Parameters / "decimal_to_binary64" { input:(Ref StringValue NonNullable) } => I64;
    BigIntArithmetic / BigIntArithmeticArguments / BigIntArithmeticParameters / "bigint_arithmetic" { left:Value,right:Value,operation:I32 } => Completion;
    TemporalCalendarIsoDateProbe / TemporalCalendarIsoDateProbeArguments / TemporalCalendarIsoDateProbeParameters / "temporal_calendar_iso_date_probe" { input:(Ref StringValue NonNullable),rewrite:I32,caller_environment:(Ref Environment Nullable) } => Completion;
    TemporalCalendarIdentifier / TemporalCalendarIdentifierArguments / TemporalCalendarIdentifierParameters / "temporal_calendar_identifier" { input:(Ref StringValue NonNullable),caller_environment:(Ref Environment Nullable) } => Completion;
    TemporalZonedDateTimeConvert / TemporalZonedDateTimeConvertArguments / TemporalZonedDateTimeConvertParameters / "temporal_zoned_date_time_convert" { input:Value,options:Value,caller_function_context:(Ref FunctionContext NonNullable),caller_environment:(Ref Environment Nullable) } => Completion;
    TemporalPlainDateConvert / TemporalPlainDateConvertArguments / TemporalPlainDateConvertParameters / "temporal_plain_date_convert" { input:Value,overflow_options:OptionalValue,caller_function_context:(Ref FunctionContext NonNullable),caller_environment:(Ref Environment Nullable) } => Completion;
    TemporalChineseYear / TemporalChineseYearArguments / TemporalChineseYearParameters / "temporal_chinese_year" { year:I64 } => EastAsianYear;
    TemporalDangiYear / TemporalDangiYearArguments / TemporalDangiYearParameters / "temporal_dangi_year" { year:I64 } => EastAsianYear;
    TemporalUmmAlQuraYear / TemporalUmmAlQuraYearArguments / TemporalUmmAlQuraYearParameters / "temporal_umalqura_year" { year:I64 } => I64;
    TemporalUmmAlQuraEpoch / TemporalUmmAlQuraEpochArguments / TemporalUmmAlQuraEpochParameters / "temporal_umalqura_epoch" { epoch:I64 } => UmmAlQuraYear;
    TemporalCalendarProjectDate / TemporalCalendarProjectDateArguments / TemporalCalendarProjectDateParameters / "temporal_calendar_project_date" { calendar:I64,year:I64,month:I64,day:I64 } => CalendarDate;
    TemporalCalendarFieldsToIso / TemporalCalendarFieldsToIsoArguments / TemporalCalendarFieldsToIsoParameters / "temporal_calendar_fields_to_iso" { calendar:I64,year:I64,month:I64,day:I64 } => CalendarIsoDate;
    TemporalCalendarDaysInMonth / TemporalCalendarDaysInMonthArguments / TemporalCalendarDaysInMonthParameters / "temporal_calendar_days_in_month" { calendar:I64,year:I64,month:I64 } => I64;
    TemporalCalendarBalanceYearMonth / TemporalCalendarBalanceYearMonthArguments / TemporalCalendarBalanceYearMonthParameters / "temporal_calendar_balance_year_month" { calendar:I64,year:I64,month:I64 } => CalendarYearMonth;
    TemporalCalendarDifferenceDate / TemporalCalendarDifferenceDateArguments / TemporalCalendarDifferenceDateParameters / "temporal_calendar_difference_date" { calendar:I64,left_year:I64,left_month:I64,left_day:I64,right_year:I64,right_month:I64,right_day:I64,largest:I64 } => CalendarDifference;
    IndexedElementRead / IndexedElementReadArguments / IndexedElementReadParameters / "indexed_element_read" { target:Value,index:I64,caller_environment:(Ref Environment Nullable) } => Completion;
    IndexedElementWrite / IndexedElementWriteArguments / IndexedElementWriteParameters / "indexed_element_write" { target:Value,index:I64,key:Key,value:Value,strict:I32,caller_environment:(Ref Environment Nullable) } => Completion;
    ValueToPrimitiveDefault / ValueToPrimitiveDefaultArguments / ValueToPrimitiveDefaultParameters / "value_to_primitive_default" { input:Value,caller_environment:(Ref Environment Nullable) } => Completion;
    ValueToPrimitiveNumber / ValueToPrimitiveNumberArguments / ValueToPrimitiveNumberParameters / "value_to_primitive_number" { input:Value,caller_environment:(Ref Environment Nullable) } => Completion;
    ValueToPrimitiveString / ValueToPrimitiveStringArguments / ValueToPrimitiveStringParameters / "value_to_primitive_string" { input:Value,caller_environment:(Ref Environment Nullable) } => Completion;
    ValueToPropertyKey / ValueToPropertyKeyArguments / ValueToPropertyKeyParameters / "value_to_property_key" { input:Value,caller_environment:(Ref Environment Nullable) } => Completion;
    ObjectHasProperty / ObjectHasPropertyArguments / ObjectHasPropertyParameters / "object_has_property" { target:Value,key:Key,caller_environment:(Ref Environment Nullable) } => Completion;
    WithEnvironmentHasBinding / WithEnvironmentHasBindingArguments / WithEnvironmentHasBindingParameters / "with_environment_has_binding" { target:Value,name:(Ref StringValue NonNullable),caller_environment:(Ref Environment Nullable) } => Completion;
    RegExpCompiler / RegExpCompilerArguments / RegExpCompilerParameters / "regexp_compiler" { source:(Ref StringValue NonNullable),flags:(Ref StringValue NonNullable) } => RegExpCompile;
    ModuleInitialize / ModuleInitializeArguments / ModuleInitializeParameters / "module_initialize" { realm:(Ref RealmRecord NonNullable) } => Completion;
    ModuleEvaluate / ModuleEvaluateArguments / ModuleEvaluateParameters / "module_evaluate" { module:(Ref ModuleRecord NonNullable) } => Completion;
    ModuleReady / ModuleReadyArguments / ModuleReadyParameters / "module_ready" { module:(Ref ModuleRecord NonNullable) } => I32;
    ModuleGather / ModuleGatherArguments / ModuleGatherParameters / "module_gather" { module:(Ref ModuleRecord NonNullable) } => ModuleGather;
    ModuleExecute / ModuleExecuteArguments / ModuleExecuteParameters / "module_execute" { module:(Ref ModuleRecord NonNullable) } => Completion;
    ModuleFulfilled / ModuleFulfilledArguments / ModuleFulfilledParameters / "module_fulfilled" { module:(Ref ModuleRecord NonNullable),value:Value } => Completion;
    ModuleRejected / ModuleRejectedArguments / ModuleRejectedParameters / "module_rejected" { module:(Ref ModuleRecord NonNullable),reason:Value } => Completion;
    ModuleDeferredImport / ModuleDeferredImportArguments / ModuleDeferredImportParameters / "module_deferred_import" { module:(Ref ModuleRecord NonNullable),caller_environment:(Ref Environment Nullable) } => Completion;
    PreparedDynamicFunction / PreparedDynamicFunctionArguments / PreparedDynamicFunctionParameters / "prepared_dynamic_function" { kind:I32,new_target:Value,sources:(Ref ValueArray NonNullable),caller_function_context:(Ref FunctionContext NonNullable),caller_environment:(Ref Environment Nullable) } => StatusCompletion;
    PreparedScript / PreparedScriptArguments / PreparedScriptParameters / "prepared_script" { kind:I32,source:(Ref StringValue NonNullable),realm:(Ref RealmRecord NonNullable) } => StatusCompletion;
    RealmModuleImport / RealmModuleImportArguments / RealmModuleImportParameters / "realm_module_import" { realm:(Ref RealmRecord NonNullable),specifier:(Ref StringValue NonNullable),caller_environment:(Ref Environment Nullable) } => RealmImport;
    ModuleBodyReaction / ModuleBodyReactionArguments / ModuleBodyReactionParameters / "module_body_reaction" { module:(Ref ModuleRecord NonNullable),rejected:I32,argument:Value } => Void;
    RegExpProgramCandidate / RegExpProgramCandidateArguments / RegExpProgramCandidateParameters / "regexp_program_candidate" { source:(Ref StringValue NonNullable),flags:(Ref StringValue NonNullable) } => RegExpCompile;
    RuntimeErrorObject / RuntimeErrorObjectArguments / RuntimeErrorObjectParameters / "runtime_error_object" { prototype:Value,message:(Ref StringValue NonNullable) } => (Ref NativeErrorObject NonNullable);
    PooledStringsInitialize / PooledStringsInitializeArguments / PooledStringsInitializeParameters / "pooled_strings_initialize" { program_strings:I32 } => Void;
    ObjectSetPrototypeOf / ObjectSetPrototypeOfArguments / ObjectSetPrototypeOfParameters / "object_set_prototype_of" { target:Value,prototype:Value,caller_environment:(Ref Environment Nullable) } => Completion;
    ObjectDelete / ObjectDeleteArguments / ObjectDeleteParameters / "object_delete" { target:Value,key:Key,caller_environment:(Ref Environment Nullable) } => Completion;
    AsyncGeneratorStartBody / AsyncGeneratorStartBodyArguments / AsyncGeneratorStartBodyParameters / "async_generator_start_body" { activation:(Ref AsyncGeneratorActivation NonNullable),pending:Completion,caller_environment:(Ref Environment Nullable) } => Completion;
    AsyncGeneratorDrainQueue / AsyncGeneratorDrainQueueArguments / AsyncGeneratorDrainQueueParameters / "async_generator_drain_queue" { activation:(Ref AsyncGeneratorActivation NonNullable),caller_environment:(Ref Environment Nullable) } => Completion;
    PromiseDrainJobs / PromiseDrainJobsArguments / PromiseDrainJobsParameters / "promise_drain_jobs" { pending:Completion,caller_environment:(Ref Environment Nullable) } => Completion;
    AsyncAwaitReactions / AsyncAwaitReactionsArguments / AsyncAwaitReactionsParameters / "async_await_reactions" { activation:(Ref AsyncActivation NonNullable),value:Value,caller_environment:(Ref Environment Nullable) } => Completion;
    AsyncGeneratorAwaitReactions / AsyncGeneratorAwaitReactionsArguments / AsyncGeneratorAwaitReactionsParameters / "async_generator_await_reactions" { activation:(Ref AsyncGeneratorActivation NonNullable),value:Value,caller_environment:(Ref Environment Nullable) } => Completion;
    AsyncGeneratorYieldReactions / AsyncGeneratorYieldReactionsArguments / AsyncGeneratorYieldReactionsParameters / "async_generator_yield_reactions" { activation:(Ref AsyncGeneratorActivation NonNullable),value:Value,caller_environment:(Ref Environment Nullable) } => Completion;
    AsyncGeneratorYieldReturnReactions / AsyncGeneratorYieldReturnReactionsArguments / AsyncGeneratorYieldReturnReactionsParameters / "async_generator_yield_return_reactions" { activation:(Ref AsyncGeneratorActivation NonNullable),value:Value,caller_environment:(Ref Environment Nullable) } => Completion;
    AsyncGeneratorAwaitReturnReactions / AsyncGeneratorAwaitReturnReactionsArguments / AsyncGeneratorAwaitReturnReactionsParameters / "async_generator_await_return_reactions" { activation:(Ref AsyncGeneratorActivation NonNullable),value:Value,caller_environment:(Ref Environment Nullable) } => Completion;
    GlobalIdentifierReadSloppy / GlobalIdentifierReadSloppyArguments / GlobalIdentifierReadSloppyParameters / "global_identifier_read_sloppy" { name:(Ref StringValue NonNullable),global_environment:(Ref Environment NonNullable),caller_execution_realm:(Ref RealmRecord NonNullable),caller_environment:(Ref Environment Nullable) } => Completion;
    GlobalIdentifierReadStrict / GlobalIdentifierReadStrictArguments / GlobalIdentifierReadStrictParameters / "global_identifier_read_strict" { name:(Ref StringValue NonNullable),global_environment:(Ref Environment NonNullable),caller_execution_realm:(Ref RealmRecord NonNullable),caller_environment:(Ref Environment Nullable) } => Completion;
    GlobalIdentifierTypeofSloppy / GlobalIdentifierTypeofSloppyArguments / GlobalIdentifierTypeofSloppyParameters / "global_identifier_typeof_sloppy" { name:(Ref StringValue NonNullable),global_environment:(Ref Environment NonNullable),caller_execution_realm:(Ref RealmRecord NonNullable),caller_environment:(Ref Environment Nullable) } => Completion;
    GlobalIdentifierTypeofStrict / GlobalIdentifierTypeofStrictArguments / GlobalIdentifierTypeofStrictParameters / "global_identifier_typeof_strict" { name:(Ref StringValue NonNullable),global_environment:(Ref Environment NonNullable),caller_execution_realm:(Ref RealmRecord NonNullable),caller_environment:(Ref Environment Nullable) } => Completion;
    PrivateElementAdd / PrivateElementAddArguments / PrivateElementAddParameters / "private_element_add" { receiver:Value,element:(Ref PrivateElement NonNullable),caller_execution_realm:(Ref RealmRecord NonNullable) } => Completion;
    PrivateFieldDefine / PrivateFieldDefineArguments / PrivateFieldDefineParameters / "private_field_define" { receiver:Value,private_environment:(Ref PrivateEnvironment Nullable),class_scope:I64,name_ordinal:I32,value:Value,caller_execution_realm:(Ref RealmRecord NonNullable) } => Completion;
    JsonStringifyValue / JsonStringifyValueArguments / JsonStringifyValueParameters / "json_stringify_value" { holder:Value,key:(Ref StringValue NonNullable),context:(Ref JsonStringifyContext NonNullable),indent:I64,seen:(Ref ValueArray NonNullable) } => Completion;
}

impl RuntimeHelperId {
    pub(crate) const fn for_east_asian_year(
        calendar: crate::data::TemporalEastAsianCalendar,
    ) -> Self {
        match calendar {
            crate::data::TemporalEastAsianCalendar::Chinese => Self::TemporalChineseYear,
            crate::data::TemporalEastAsianCalendar::Dangi => Self::TemporalDangiYear,
        }
    }
    pub(crate) const fn helper_for(hint: ToPrimitiveHint) -> Self {
        match hint {
            ToPrimitiveHint::Default => Self::ValueToPrimitiveDefault,
            ToPrimitiveHint::Number => Self::ValueToPrimitiveNumber,
            ToPrimitiveHint::String => Self::ValueToPrimitiveString,
        }
    }
    pub(crate) const fn owner(self) -> HelperOwner {
        match self {
            Self::TransientByteAlloc => HelperOwner::Runtime,
            Self::ArrayIndexedPublish => HelperOwner::Runtime,
            Self::ArrayIndexedDelete => HelperOwner::Runtime,
            Self::ObjectRead => HelperOwner::Runtime,
            Self::ObjectWrite => HelperOwner::Runtime,
            Self::ObjectDefineData => HelperOwner::Runtime,
            Self::OrdinaryPropertyAppend => HelperOwner::Runtime,
            Self::ObjectHeaderProjection => HelperOwner::Runtime,
            Self::OrdinaryObjectAllocate => HelperOwner::Runtime,
            Self::ValueToObject => HelperOwner::Runtime,
            Self::FunctionMetadataPublish => HelperOwner::Runtime,
            Self::RealmInitializeIntrinsics => HelperOwner::Runtime,
            Self::ProxyCall => HelperOwner::Runtime,
            Self::ProxyConstruct => HelperOwner::Runtime,
            Self::StringEquality => HelperOwner::Runtime,
            Self::NumberToString => HelperOwner::Runtime,
            Self::StringToNumber => HelperOwner::Runtime,
            Self::ValueToString => HelperOwner::Runtime,
            Self::ValueToNumber => HelperOwner::Runtime,
            Self::ValueToNumeric => HelperOwner::Runtime,
            Self::CoerciveAdd => HelperOwner::Runtime,
            Self::ObjectGetPrototypeOf => HelperOwner::Runtime,
            Self::ObjectIsExtensible => HelperOwner::Runtime,
            Self::ObjectPreventExtensions => HelperOwner::Runtime,
            Self::ObjectReadProxy => HelperOwner::Runtime,
            Self::RegExpMatcher => HelperOwner::Runtime,
            Self::FunctionCall => HelperOwner::Runtime,
            Self::DynamicPropertyRead => HelperOwner::Runtime,
            Self::OrdinarySetDataOnReceiver => HelperOwner::Runtime,
            Self::OrdinarySet => HelperOwner::Runtime,
            Self::DecimalToBinary64 => HelperOwner::Runtime,
            Self::BigIntArithmetic => HelperOwner::Runtime,
            Self::TemporalCalendarIsoDateProbe => HelperOwner::Runtime,
            Self::TemporalCalendarIdentifier => HelperOwner::Runtime,
            Self::TemporalZonedDateTimeConvert => HelperOwner::Runtime,
            Self::TemporalPlainDateConvert => HelperOwner::Runtime,
            Self::TemporalChineseYear => HelperOwner::Runtime,
            Self::TemporalDangiYear => HelperOwner::Runtime,
            Self::TemporalUmmAlQuraYear => HelperOwner::Runtime,
            Self::TemporalUmmAlQuraEpoch => HelperOwner::Runtime,
            Self::TemporalCalendarProjectDate => HelperOwner::Runtime,
            Self::TemporalCalendarFieldsToIso => HelperOwner::Runtime,
            Self::TemporalCalendarDaysInMonth => HelperOwner::Runtime,
            Self::TemporalCalendarBalanceYearMonth => HelperOwner::Runtime,
            Self::TemporalCalendarDifferenceDate => HelperOwner::Runtime,
            Self::IndexedElementRead => HelperOwner::Runtime,
            Self::IndexedElementWrite => HelperOwner::Runtime,
            Self::ValueToPrimitiveDefault => HelperOwner::Runtime,
            Self::ValueToPrimitiveNumber => HelperOwner::Runtime,
            Self::ValueToPrimitiveString => HelperOwner::Runtime,
            Self::ValueToPropertyKey => HelperOwner::Runtime,
            Self::ObjectHasProperty => HelperOwner::Runtime,
            Self::WithEnvironmentHasBinding => HelperOwner::Runtime,
            Self::RegExpCompiler => HelperOwner::Runtime,
            Self::ModuleInitialize => HelperOwner::Program,
            Self::ModuleEvaluate => HelperOwner::Program,
            Self::ModuleReady => HelperOwner::Program,
            Self::ModuleGather => HelperOwner::Program,
            Self::ModuleExecute => HelperOwner::Program,
            Self::ModuleFulfilled => HelperOwner::Program,
            Self::ModuleRejected => HelperOwner::Program,
            Self::ModuleDeferredImport => HelperOwner::Program,
            Self::PreparedDynamicFunction => {
                HelperOwner::Hook(ProgramHook::PreparedDynamicFunction)
            }
            Self::PreparedScript => HelperOwner::Hook(ProgramHook::PreparedScript),
            Self::RealmModuleImport => HelperOwner::Hook(ProgramHook::RealmModuleImport),
            Self::ModuleBodyReaction => HelperOwner::Hook(ProgramHook::ModuleBodyReaction),
            Self::RegExpProgramCandidate => HelperOwner::Hook(ProgramHook::RegExpProgramCandidate),
            Self::RuntimeErrorObject => HelperOwner::Runtime,
            Self::PooledStringsInitialize => HelperOwner::Runtime,
            Self::ObjectSetPrototypeOf => HelperOwner::Runtime,
            Self::ObjectDelete => HelperOwner::Runtime,
            Self::AsyncGeneratorStartBody => HelperOwner::Runtime,
            Self::AsyncGeneratorDrainQueue => HelperOwner::Runtime,
            Self::PromiseDrainJobs => HelperOwner::Runtime,
            Self::AsyncAwaitReactions => HelperOwner::Runtime,
            Self::AsyncGeneratorAwaitReactions => HelperOwner::Runtime,
            Self::AsyncGeneratorYieldReactions => HelperOwner::Runtime,
            Self::AsyncGeneratorYieldReturnReactions => HelperOwner::Runtime,
            Self::AsyncGeneratorAwaitReturnReactions => HelperOwner::Runtime,
            Self::GlobalIdentifierReadSloppy => HelperOwner::Runtime,
            Self::GlobalIdentifierReadStrict => HelperOwner::Runtime,
            Self::GlobalIdentifierTypeofSloppy => HelperOwner::Runtime,
            Self::GlobalIdentifierTypeofStrict => HelperOwner::Runtime,
            Self::PrivateElementAdd => HelperOwner::Runtime,
            Self::PrivateFieldDefine => HelperOwner::Runtime,
            Self::JsonStringifyValue => HelperOwner::Runtime,
        }
    }
    pub(crate) const fn is_emitted(self, emission: RuntimeHelperEmission) -> bool {
        match self {
            Self::TransientByteAlloc => true,
            Self::ArrayIndexedPublish => true,
            Self::ArrayIndexedDelete => true,
            Self::ObjectRead => true,
            Self::ObjectWrite => true,
            Self::ObjectDefineData => true,
            Self::OrdinaryPropertyAppend => true,
            Self::ObjectHeaderProjection => true,
            Self::OrdinaryObjectAllocate => true,
            Self::ValueToObject => true,
            Self::FunctionMetadataPublish => true,
            Self::RealmInitializeIntrinsics => true,
            Self::ProxyCall => true,
            Self::ProxyConstruct => true,
            Self::StringEquality => true,
            Self::NumberToString => true,
            Self::StringToNumber => true,
            Self::ValueToString => true,
            Self::ValueToNumber => true,
            Self::ValueToNumeric => true,
            Self::CoerciveAdd => true,
            Self::ObjectGetPrototypeOf => true,
            Self::ObjectIsExtensible => true,
            Self::ObjectPreventExtensions => true,
            Self::ObjectReadProxy => true,
            Self::RegExpMatcher => true,
            Self::FunctionCall => true,
            Self::DynamicPropertyRead => true,
            Self::OrdinarySetDataOnReceiver => true,
            Self::OrdinarySet => true,
            Self::DecimalToBinary64 => true,
            Self::BigIntArithmetic => true,
            Self::TemporalCalendarIsoDateProbe => true,
            Self::TemporalCalendarIdentifier => true,
            Self::TemporalZonedDateTimeConvert => true,
            Self::TemporalPlainDateConvert => true,
            Self::TemporalChineseYear => true,
            Self::TemporalDangiYear => true,
            Self::TemporalUmmAlQuraYear => true,
            Self::TemporalUmmAlQuraEpoch => true,
            Self::TemporalCalendarProjectDate => true,
            Self::TemporalCalendarFieldsToIso => true,
            Self::TemporalCalendarDaysInMonth => true,
            Self::TemporalCalendarBalanceYearMonth => true,
            Self::TemporalCalendarDifferenceDate => true,
            Self::IndexedElementRead => true,
            Self::IndexedElementWrite => true,
            Self::ValueToPrimitiveDefault => true,
            Self::ValueToPrimitiveNumber => true,
            Self::ValueToPrimitiveString => true,
            Self::ValueToPropertyKey => true,
            Self::ObjectHasProperty => true,
            Self::WithEnvironmentHasBinding => true,
            Self::GlobalIdentifierReadSloppy => true,
            Self::GlobalIdentifierReadStrict => true,
            Self::GlobalIdentifierTypeofSloppy => true,
            Self::GlobalIdentifierTypeofStrict => true,
            Self::PrivateElementAdd => true,
            Self::PrivateFieldDefine => true,
            Self::RegExpCompiler => true,
            Self::ModuleInitialize => true,
            Self::ModuleEvaluate => true,
            Self::ModuleReady => true,
            Self::ModuleGather => true,
            Self::ModuleExecute => true,
            Self::ModuleFulfilled => true,
            Self::ModuleRejected => true,
            Self::ModuleDeferredImport => true,
            Self::PreparedDynamicFunction => true,
            Self::PreparedScript => true,
            Self::RealmModuleImport => true,
            Self::ModuleBodyReaction => true,
            Self::RegExpProgramCandidate => true,
            Self::RuntimeErrorObject => true,
            Self::PooledStringsInitialize => true,
            Self::ObjectSetPrototypeOf => true,
            Self::ObjectDelete => true,
            Self::AsyncGeneratorStartBody => true,
            Self::AsyncGeneratorDrainQueue => true,
            Self::PromiseDrainJobs => true,
            Self::AsyncAwaitReactions => true,
            Self::AsyncGeneratorAwaitReactions => true,
            Self::AsyncGeneratorYieldReactions => true,
            Self::AsyncGeneratorYieldReturnReactions => true,
            Self::AsyncGeneratorAwaitReturnReactions => true,
            Self::JsonStringifyValue => emission.holds(RuntimeHelperFact::UsesJsonStringify),
        }
    }
    /// Whether the body is generated from the program and so sits after
    /// `main`.
    pub(crate) const fn is_program_owned(self) -> bool {
        matches!(self.owner().region(), HelperRegion::Program)
    }
    /// Emits the call instruction for this helper's declared route.
    ///
    /// A hook is reached only through its global and a program-owned helper
    /// only by `call`, so a mismatched route is a compiler bug, not input.
    pub(crate) fn emit_invocation(
        self,
        schema: &RuntimeSchema,
        route: HelperRoute,
        function: &mut Function,
    ) {
        match (self.owner(), route) {
            (HelperOwner::Runtime | HelperOwner::Program, HelperRoute::Direct(base)) => {
                function.instruction(&Instruction::Call(self.index(base)));
            }
            (HelperOwner::Hook(hook), HelperRoute::Hook) => {
                function.instruction(&Instruction::GlobalGet(schema.program_hook_global(hook)));
                function.instruction(&Instruction::CallRef(self.type_index()));
            }
            (HelperOwner::Hook(_), HelperRoute::Direct(_)) => panic!(
                "program hook `{}` must be called through its hook global",
                self.debug_name()
            ),
            (HelperOwner::Runtime | HelperOwner::Program, HelperRoute::Hook) => {
                panic!("helper `{}` is not a program hook", self.debug_name())
            }
        }
    }
    pub(crate) const fn is_conditional(self) -> bool {
        !self.is_emitted(RuntimeHelperEmission::NONE)
    }
    const fn conditional_helpers_are_last() -> bool {
        let mut index = 0;
        let mut omitted = false;
        while index < Self::ALL.len() {
            if Self::ALL[index].is_conditional() {
                omitted = true;
            } else if omitted {
                return false;
            }
            index += 1;
        }
        true
    }
}
const _: () = assert!(RuntimeHelperId::conditional_helpers_are_last());

impl RuntimeSchema {
    pub(crate) fn call_helper<A: HelperArguments>(
        &self,
        arguments: A,
        base: RuntimeHelperFunctionBase,
        function: &mut Function,
    ) -> A::Result {
        arguments.emit_call(self, HelperRoute::Direct(base), function)
    }
    /// Calls a program hook through its global. The token proves the caller
    /// branched on the hook being installed.
    pub(crate) fn call_hook<A: HelperArguments>(
        &self,
        hook: &InstalledHook,
        arguments: A,
        function: &mut Function,
    ) -> A::Result {
        assert_eq!(
            hook.hook.helper(),
            A::ID,
            "hook token must match its helper"
        );
        arguments.emit_call(self, HelperRoute::Hook, function)
    }
    pub(crate) fn helper_parameters<P: HelperParameters>(&self, function: &mut Function) -> P {
        P::acquire(self, function)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn regexp_matcher_status_domain_owns_words_routes_and_messages() {
        assert_eq!(
            RegExpMatcherStatus::ALL,
            &[
                RegExpMatcherStatus::Complete,
                RegExpMatcherStatus::Failed(RegExpMatcherFailure::CorruptProgram),
                RegExpMatcherStatus::Failed(RegExpMatcherFailure::ResourceExhausted),
            ]
        );
        assert_eq!(
            RegExpMatcherStatus::ALL
                .iter()
                .copied()
                .map(RegExpMatcherStatus::abi_word)
                .collect::<Vec<_>>(),
            vec![0, 1, 2]
        );
        assert_eq!(
            RegExpMatcherFailure::ALL
                .iter()
                .copied()
                .map(|failure| match failure.route() {
                    RegExpMatcherFailureRoute::GenericError => "generic-error",
                    RegExpMatcherFailureRoute::CurrentFunctionRealmRangeError => {
                        "current-function-realm-range-error"
                    }
                })
                .collect::<Vec<_>>(),
            vec!["generic-error", "current-function-realm-range-error"]
        );
        for failure in RegExpMatcherFailure::ALL {
            assert!(failure
                .message()
                .catalog_text()
                .is_some_and(|text| !text.is_empty()));
        }
    }

    #[test]
    fn indexes_are_dense_from_the_base() {
        let base = RuntimeHelperFunctionBase::at(100, 1000);
        let mut runtime = 0;
        let mut program = 0;
        for helper in RuntimeHelperId::ALL {
            match helper.owner() {
                HelperOwner::Runtime => {
                    assert_eq!(helper.index(base), 100 + runtime);
                    runtime += 1;
                }
                HelperOwner::Program | HelperOwner::Hook(_) => {
                    assert_eq!(helper.index(base), 1000 + program);
                    program += 1;
                }
            }
        }
    }

    #[test]
    fn every_hook_names_the_helper_that_names_it() {
        for hook in ProgramHook::ALL {
            assert_eq!(hook.helper().owner(), HelperOwner::Hook(hook));
        }
        let hooked = RuntimeHelperId::ALL
            .iter()
            .filter(|helper| matches!(helper.owner(), HelperOwner::Hook(_)))
            .count();
        assert_eq!(hooked, ProgramHook::ALL.len());
    }

    #[test]
    fn debug_names_are_unique() {
        let mut names = std::collections::BTreeSet::new();
        for helper in RuntimeHelperId::ALL {
            assert!(
                names.insert(helper.debug_name()),
                "duplicate runtime helper name {}",
                helper.debug_name()
            );
        }
        assert_eq!(names.len(), RuntimeHelperId::ALL.len());
    }

    #[test]
    fn json_stringify_is_the_only_conditional_helper() {
        let conditional = RuntimeHelperId::ALL
            .iter()
            .copied()
            .filter(|helper| helper.is_conditional())
            .collect::<Vec<_>>();
        assert_eq!(conditional, vec![RuntimeHelperId::JsonStringifyValue]);
    }

    /// Every hint names a distinct body, and every body is a real helper in
    /// `ALL`. Without the second half a hint could name a variant that the
    /// function/code sections never write, which would hand every ToPrimitive
    /// call site an index one past the end of the helper block.
    #[test]
    fn every_to_primitive_hint_names_its_own_helper() {
        let helpers = [
            ToPrimitiveHint::Default,
            ToPrimitiveHint::Number,
            ToPrimitiveHint::String,
        ]
        .map(RuntimeHelperId::helper_for);
        assert_eq!(
            helpers,
            [
                RuntimeHelperId::ValueToPrimitiveDefault,
                RuntimeHelperId::ValueToPrimitiveNumber,
                RuntimeHelperId::ValueToPrimitiveString,
            ]
        );
        for helper in helpers {
            assert!(
                RuntimeHelperId::ALL.contains(&helper),
                "{helper:?} is not in ALL, so its body is never emitted"
            );
            assert!(
                helper.is_emitted(RuntimeHelperEmission::NONE),
                "{helper:?} must be unconditional: the ToPrimitive seam has no \
                 emission fact to gate on"
            );
        }
    }

    /// `NONE` is the input `is_conditional` is defined against, so "no fact
    /// holds in it" is what makes a conditional helper detectable at all.
    #[test]
    fn the_empty_emission_context_holds_no_fact() {
        for fact in [RuntimeHelperFact::UsesJsonStringify] {
            assert!(!RuntimeHelperEmission::NONE.holds(fact), "{fact:?}");
            assert!(RuntimeHelperEmission::NONE.with(fact, true).holds(fact));
            assert_eq!(
                RuntimeHelperEmission::NONE.with(fact, false),
                RuntimeHelperEmission::NONE
            );
        }
    }
}
