// Generated by scripts/generate-intl-segmenter-identity.py.
pub const SEGMENTER_DATA_SHA256: &str =
    "1ebd5c1bb3f75ca68a20d5021e5a494d6ba169f5e75dcc65cea782ddbcd32dae";
pub(super) const SEGMENTER_SOURCE_MANIFEST_SHA256: &str =
    "8612f2eb0857fab45863f717f63e95220274747717549f92b2f1af394f067cbe";
