#!/usr/bin/env python3
"""Generate DateTimeFormat positional digits from hash-pinned CLDR 47 XML."""

import argparse
import hashlib
import json
from pathlib import Path
import re
import xml.etree.ElementTree as ET

REPOSITORY = Path(__file__).resolve().parents[1]
SOURCE_PATH = "crates/lila-aot-wasm/data/cldr-47-numbering"
OUTPUT_PATH = "crates/lila-aot-wasm/src/builtins/intl_datetimeformat/numbering_systems/generated.rs"
SYMBOL_ALIAS = re.compile(r"\.\./symbols\[@numberSystem='([a-z0-9]{3,8})'\]")


def generate(source_dir):
    manifest = json.loads((source_dir / "manifest.json").read_text())
    if manifest["release"] != "47.0.0":
        raise ValueError("review the pinned CLDR version before regeneration")
    documents = {}
    for entry in manifest["files"]:
        contents = (source_dir / entry["path"]).read_bytes()
        if hashlib.sha256(contents).hexdigest() != entry["sha256"]:
            raise ValueError(f"upstream source checksum mismatch: {entry['path']}")
        if entry["path"].endswith(".xml"):
            documents[entry["path"]] = ET.fromstring(contents)
    if set(documents) != {
        "common/supplemental/numberingSystems.xml",
        "common/main/root.xml",
        "common/main/en.xml",
    }:
        raise ValueError("numbering source manifest and generator disagree")

    locales = {
        locale: documents[f"common/main/{locale}.xml"] for locale in ("en", "root")
    }

    def decimal_separator(identifier, seen=()):
        if identifier in seen:
            raise ValueError(f"cyclic symbol alias: {identifier}")
        for locale in ("en", "root"):
            symbols = locales[locale].find(f"./numbers/symbols[@numberSystem='{identifier}']")
            if symbols is None:
                continue
            decimal = symbols.find("decimal")
            if decimal is not None:
                if decimal.text in (None, "", "↑↑↑"):
                    raise ValueError(f"unresolved decimal inheritance: {locale}/{identifier}")
                return decimal.text
            alias = symbols.find("alias")
            if alias is not None:
                target = SYMBOL_ALIAS.fullmatch(alias.attrib["path"])
                if alias.attrib["source"] != "locale" or target is None:
                    raise ValueError(f"unsupported symbol alias: {locale}/{identifier}")
                return decimal_separator(target[1], (*seen, identifier))
        raise ValueError(f"missing decimal separator: {identifier}")

    rows = []
    excluded = []
    identifiers = set()
    for system in documents["common/supplemental/numberingSystems.xml"].findall(
        "./numberingSystems/numberingSystem"
    ):
        identifier = system.attrib["id"]
        if identifier in identifiers or not re.fullmatch(r"[a-z0-9]{3,8}", identifier):
            raise ValueError(f"invalid or duplicate numbering identifier: {identifier}")
        identifiers.add(identifier)
        kind = system.attrib["type"]
        if kind == "algorithmic":
            if not system.get("rules") or "digits" in system.attrib:
                raise ValueError(f"invalid algorithmic numbering system: {identifier}")
            excluded.append(identifier)
            continue
        if kind != "numeric" or "rules" in system.attrib:
            raise ValueError(f"unknown numbering system kind: {identifier}/{kind}")
        digits = system.attrib["digits"]
        if len(digits) != 10 or len(set(digits)) != 10:
            raise ValueError(f"numbering system must have ten distinct digits: {identifier}")
        if len({len(digit.encode("utf-8")) for digit in digits}) != 1:
            raise ValueError(f"variable UTF-8 digit widths require a new renderer: {identifier}")
        rows.append((identifier, digits, decimal_separator(identifier)))
    rows.sort()
    default_index = next(index for index, row in enumerate(rows) if row[0] == "latn")
    lines = [
        "// Generated by scripts/generate-intl-datetime-numbering.py; do not edit.",
        f"// CLDR {manifest['release']}, commit {manifest['commit']}.",
        "// Sources, checksums and Unicode license: data/cldr-47-numbering/.",
        "use super::DtfNumberingSystem;",
        "",
        f"pub(super) const DEFAULT_INDEX: usize = {default_index};",
        "",
        f"pub(in super::super) const NUMBERING_SYSTEMS: [DtfNumberingSystem; {len(rows)}] = [",
    ]
    for identifier, digits, decimal in rows:
        # CLDR identifiers, digit characters and decimal symbols in this pinned
        # domain require no Rust string escapes. Reject a changed source rather
        # than allowing a generator to introduce invalid literals.
        for value in (identifier, digits, decimal):
            if any(char in value for char in ('"', "\\", "\n", "\r")):
                raise ValueError("new source requires Rust string literal escaping")
        lines.append(f'    DtfNumberingSystem::new("{identifier}", "{digits}", "{decimal}"),')
    lines.extend(["];", ""])
    report = {
        "cldr_release": manifest["release"],
        "cldr_commit": manifest["commit"],
        "positional_numbering_systems": len(rows),
        "excluded_algorithmic_numbering_systems": sorted(excluded),
        "locale_patterns": ["en", "en-US"],
        "decimal_symbols_resolved_from": ["en", "root"],
        "default_numbering_system": rows[default_index][0],
    }
    return "\n".join(lines), json.dumps(report, indent=2) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-dir", type=Path, default=REPOSITORY / SOURCE_PATH)
    parser.add_argument("--output", type=Path, default=REPOSITORY / OUTPUT_PATH)
    parser.add_argument("--report", type=Path)
    parser.add_argument("--check", action="store_true")
    options = parser.parse_args()
    generated, report = generate(options.source_dir)
    for path, contents in ((options.output, generated), (options.report, report)):
        if path is None:
            continue
        if options.check:
            if path.read_text() != contents:
                raise SystemExit(f"generated file is stale: {path}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(contents)


if __name__ == "__main__":
    main()
