#!/usr/bin/env python3
"""Derive shortcut accounting from canonical audit inputs, not Test262 results."""
from __future__ import annotations

import argparse
from collections import Counter
import hashlib
from pathlib import Path
import re
import sys

REASONS = {
    'legitimate-harness-adaptation': {'upstream-harness-materialization', 'suite-selection'},
    'diagnostic-instrumentation': {'artifact-routing', 'unsupported-feature-routing', 'vendored-contract-guard'},
    'semantic-shortcut': {'test-specific-materialization', 'reduced-harness-helper', 'source-shape-rewrite', 'dynamic-source-substitution'},
}
LEDGER = Path('test262/backlog/shortcut-allowlist.tsv')
INVENTORY = Path('test262/backlog/shortcut-inventory.md')
SOURCE = Path('crates/lila-test262/src/lib.rs')
OUTPUT = Path('test262/backlog/current-shortcut-status.md')
KEY = re.compile(r'(path-rewrite-entrypoint|direct-path-predicate|source-text-predicate|harness-helper-reduction)/[A-Za-z0-9_]+/[0-9]{3}')


def ledger_rows(text: str) -> list[tuple[str, ...]]:
    rows: list[tuple[str, ...]] = []
    seen: set[str] = set()
    for number, line in enumerate(text.splitlines(), 1):
        if not line or line.startswith('#'):
            continue
        row = tuple(line.split('\t'))
        if len(row) != 6:
            raise ValueError(f'ledger line {number}: expected exactly six fields')
        key, fingerprint, classification, owner, removal, reason = row
        if not KEY.fullmatch(key) or key in seen:
            raise ValueError(f'ledger line {number}: invalid or duplicate key {key!r}')
        if not re.fullmatch(r'[0-9a-f]{64}', fingerprint):
            raise ValueError(f'ledger line {number}: invalid fingerprint')
        if classification not in REASONS or reason not in REASONS[classification]:
            raise ValueError(f'ledger line {number}: invalid classification/reason pair')
        if any(not re.fullmatch(r'T[0-2][0-9]', task) for task in (owner, removal)):
            raise ValueError(f'ledger line {number}: invalid concrete task owner')
        seen.add(key)
        rows.append(row)
    if not rows:
        raise ValueError('refusing an empty shortcut ledger')
    return rows


def inventory_counts(text: str) -> dict[str, int]:
    marker = '## Classification summary\n'
    if text.count(marker) != 1:
        raise ValueError('inventory must have exactly one classification summary')
    section = text.split(marker, 1)[1].split('\n## ', 1)[0]
    lines = [line for line in section.splitlines() if line.strip()]
    if lines[:2] != ['| Classification | Count |', '| --- | ---: |']:
        raise ValueError('invalid inventory classification table header')
    counts: dict[str, int] = {}
    for line in lines[2:]:
        match = re.fullmatch(r'\| `([^`]+)` \| (0|[1-9][0-9]*) \|', line)
        if not match or match[1] not in REASONS or match[1] in counts:
            raise ValueError('invalid, unknown or duplicate inventory classification row')
        counts[match[1]] = int(match[2])
    if set(counts) != set(REASONS):
        raise ValueError('incomplete inventory classification table')
    return counts


def render(root: Path) -> str:
    ledger = (root / LEDGER).read_bytes()
    inventory = (root / INVENTORY).read_bytes()
    source = (root / SOURCE).read_bytes()
    rows = ledger_rows(ledger.decode('utf-8'))
    counts = {kind: sum(row[2] == kind for row in rows) for kind in REASONS}
    if inventory_counts(inventory.decode('utf-8')) != counts:
        raise ValueError('ledger/inventory counts differ; regenerate the source audit first')
    lines = [
        '# Current shortcut accounting', '',
        'Generated by `python3 scripts/generate-shortcut-status.py`; do not edit counts by hand.', '',
        'This is an inventory of classified source observations, not a Test262 pass rate,',
        'a count of independent bugs, or a project completion percentage. A green source',
        'audit means no unclassified selector drift; it does not mean zero shortcuts.', '',
        '## Classification summary', '', '| Classification | Observations |', '| --- | ---: |',
    ]
    lines.extend(f'| `{kind}` | {counts[kind]} |' for kind in REASONS)
    lines.extend([f'| **Total** | **{len(rows)}** |', '', '## Semantic shortcuts by removal task', '',
                  'Only `semantic-shortcut` observations appear below. The canonical inventory',
                  'also groups legitimate adaptations and diagnostic observations by task.', '',
                  '| Removal task | Semantic observations |', '| --- | ---: |'])
    removals = Counter(row[4] for row in rows if row[2] == 'semantic-shortcut')
    lines.extend(f'| {task} | {count} |' for task, count in sorted(removals.items()))
    if not removals:
        lines.append('| None | 0 |')
    lines.extend(['', '## Input identity', '', '| Input | SHA-256 |', '| --- | --- |'])
    for path, data in ((LEDGER, ledger), (INVENTORY, inventory), (SOURCE, source)):
        lines.append(f'| `{path.as_posix()}` | `{hashlib.sha256(data).hexdigest()}` |')
    lines.extend(['', 'Run `bash scripts/audit-test262-shortcuts.sh --check` before regenerating this',
                  'report. CI runs that source-level audit as well as `--check` on this generator.',
                  'The generator alone cross-checks the committed ledger and inventory; it does',
                  'not replace the Rust selector scanner or verify every recorded classification.', '',
                  'Full-suite evidence and native snapshot provenance remain governed by',
                  '[T01](../../tasks/01-baseline-and-generated-backlog.md) and',
                  '[T26](../../tasks/26-zero-failure-conformance-closure.md). Only the Rust publisher',
                  'owns canonical Test262 result counts and the generated README conformance block.', ''])
    return '\n'.join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--root', type=Path, default=Path(__file__).resolve().parent.parent)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    try:
        report = render(args.root)
        destination = args.root / OUTPUT
        if args.check:
            if not destination.is_file() or destination.read_text(encoding='utf-8') != report:
                raise ValueError('current shortcut status is missing or stale; regenerate it')
        else:
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(report, encoding='utf-8')
    except (OSError, UnicodeError, ValueError) as error:
        print(f'shortcut-status: {error}', file=sys.stderr)
        return 1
    print(f'shortcut-status: {"verified" if args.check else "generated"} {OUTPUT}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
