#!/usr/bin/env python3
"""Generate complete CLDR47 BCP47 keyword aliases from hash-pinned local XML."""
import argparse
from collections import defaultdict
import hashlib
import json
from pathlib import Path
import re
import xml.etree.ElementTree as ET

REPOSITORY = Path(__file__).resolve().parents[1]
VALUE = re.compile(r"[a-z0-9]{3,8}(?:-[a-z0-9]{3,8})*")
KEY = {"u": re.compile(r"[a-z0-9][a-z]"), "t": re.compile(r"[a-z][0-9]")}


def generate(source_dir):
    manifest_bytes = (source_dir / "manifest.json").read_bytes()
    manifest = json.loads(manifest_bytes)
    if manifest["release"] != "47.0.0":
        raise ValueError("review the provider's pinned CLDR version before regeneration")
    expected_xml = set()
    documents = []
    for entry in manifest["files"]:
        path = source_dir / entry["path"]
        payload = path.read_bytes()
        if hashlib.sha256(payload).hexdigest() != entry["sha256"]:
            raise ValueError(f"upstream source checksum mismatch: {path}")
        if path.suffix == ".xml":
            expected_xml.add(path.resolve())
            documents.append((entry["path"], ET.fromstring(payload)))
    if expected_xml != {path.resolve() for path in (source_dir / "common/bcp47").glob("*.xml")}:
        raise ValueError("BCP47 directory and pinned source manifest disagree")

    mappings = {}
    excluded = []
    duplicate_aliases = 0
    key_count = 0
    type_count = 0
    for path, document in documents:
        if document.tag != "ldmlBCP47":
            raise ValueError(f"unexpected BCP47 root in {path}")
        if document.findall(".//attribute"):
            raise ValueError("new attribute rules require an explicit canonicalization operation")
        for key in document.findall(".//key"):
            extension = key.get("extension", "u")
            name = key.attrib["name"]
            if extension not in KEY or not KEY[extension].fullmatch(name):
                raise ValueError(f"unknown extension/key domain: {extension}-{name}")
            if key.get("preferred") or any(KEY[extension].fullmatch(alias.lower())
                                           for alias in key.get("alias", "").split()):
                raise ValueError("new well-formed key aliases require key replacement support")
            key_count += 1
            types = {entry.attrib["name"].lower(): entry for entry in key.findall("type")}
            if len(types) != len(key.findall("type")):
                raise ValueError(f"duplicate type names in {path}: {name}")
            type_count += len(types)

            def preferred(source):
                seen = set()
                while types[source].get("preferred"):
                    if source in seen:
                        raise ValueError(f"cyclic preferred alias: {extension}-{name}-{source}")
                    seen.add(source)
                    source = types[source].attrib["preferred"].lower()
                    if source not in types:
                        raise ValueError(f"preferred target is unregistered: {source}")
                return source

            for source_name, entry in types.items():
                canonical = preferred(source_name)
                aliases = entry.get("alias", "").lower().split()
                if source_name != canonical:
                    aliases.append(source_name)
                for alias in aliases:
                    if alias == canonical:
                        continue
                    if not VALUE.fullmatch(alias):
                        excluded.append((path, extension, name, alias, canonical))
                        continue
                    if not VALUE.fullmatch(canonical):
                        raise ValueError(f"canonical value is not well formed: {canonical}")
                    lookup = extension, name, alias
                    if lookup in mappings:
                        if mappings[lookup] != canonical:
                            raise ValueError(f"conflicting alias: {lookup}")
                        duplicate_aliases += 1
                    mappings[lookup] = canonical

    # Every output is terminal; this makes a single lookup the complete alias pass.
    for (extension, key, alias), canonical in mappings.items():
        if (extension, key, canonical) in mappings:
            raise ValueError(f"nonterminal alias requires resolution: {extension}-{key}-{alias}")
    lines = ["// Generated by scripts/generate-intl-keyword-aliases.py; do not edit.",
             f"// CLDR {manifest['release']}, commit {manifest['commit']}.",
             "// Unicode license and all source checksums: data/cldr-47-bcp47/.",
             "use super::{TransformKeywordAliases, UnicodeKeywordAliases};", ""]
    groups = defaultdict(list)
    for (extension, key, alias), canonical in sorted(mappings.items()):
        groups[extension, key].append((alias, canonical))
    for extension, type_name, table_name in [("u", "UnicodeKeywordAliases", "UNICODE_ALIASES"),
                                             ("t", "TransformKeywordAliases", "TRANSFORM_ALIASES")]:
        lines.append(f"pub(super) const {table_name}: &[{type_name}] = &[")
        for (current, key), aliases in sorted(groups.items()):
            if current != extension:
                continue
            lines.append(f"    {type_name} {{")
            domain = "unicode" if extension == "u" else "transform"
            lines.append(f'        key: icu_locale::extensions::{domain}::key!("{key}"),')
            inline = "        replacements: &[" + ", ".join(
                f'("{alias}", "{canonical}")' for alias, canonical in aliases) + "],"
            if len(inline.removeprefix("        replacements: &")) <= 60:
                lines.append(inline)
            else:
                lines.append("        replacements: &[")
                for alias, canonical in aliases:
                    lines.append(f'            ("{alias}", "{canonical}"),')
                lines.append("        ],")
            lines.append("    },")
        lines.extend(["];", ""])
    canonical_rows = b"".join(f"{ext}\t{key}\t{alias}\t{replacement}\n".encode()
                              for (ext, key, alias), replacement in sorted(mappings.items()))
    alias_hash = hashlib.sha256(canonical_rows).digest()
    source_hash = hashlib.sha256(manifest_bytes).digest()
    archive_hash = bytes.fromhex(manifest["icu_locale_data"]["archive_sha256"])
    if len(archive_hash) != 32 or manifest["icu_locale_data"]["version"] != "2.0.0":
        raise ValueError("invalid pinned ICU locale archive identity")
    composite = hashlib.sha256(b"lila-intl-locale-provider-v2\0" + archive_hash
                               + source_hash + alias_hash).digest()
    lines.extend(["// Composite identity covers the ICU archive, source manifest and alias rows.",
                  "pub(super) const PROVIDER_DATA_SHA256: [u8; 32] = ["])
    for offset in range(0, 32, 16):
        lines.append("    " + ", ".join(f"0x{byte:02x}" for byte in composite[offset:offset+16]) + ",")
    lines.extend(["];", ""])
    report = {"cldr_release": manifest["release"], "cldr_commit": manifest["commit"],
              "source_manifest_sha256": source_hash.hex(), "alias_rows_sha256": alias_hash.hex(),
              "icu_archive_sha256": archive_hash.hex(), "provider_data_sha256": composite.hex(),
              "xml_files": len(documents), "keys": key_count, "types": type_count,
              "unicode_aliases": sum(ext == "u" for ext, _, _ in mappings),
              "transform_aliases": sum(ext == "t" for ext, _, _ in mappings),
              "equivalent_duplicate_alias_rows": duplicate_aliases,
              "excluded_legacy_syntax_aliases": [dict(zip(
                  ["source", "extension", "key", "alias", "canonical"], row)) for row in excluded]}
    return "\n".join(lines), json.dumps(report, indent=2) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-dir", type=Path,
                        default=REPOSITORY / "crates/lila-intl/data/cldr-47-bcp47")
    parser.add_argument("--output", type=Path,
                        default=REPOSITORY / "crates/lila-intl/src/provider/keyword_aliases/generated.rs")
    parser.add_argument("--report", type=Path)
    parser.add_argument("--check", action="store_true")
    options = parser.parse_args()
    generated, report = generate(options.source_dir)
    for path, contents in [(options.output, generated), (options.report, report)]:
        if path is None:
            continue
        if options.check:
            if path.read_text() != contents:
                raise ValueError(f"generated output differs: {path}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(contents)
    parsed_report = json.loads(report)
    print(f"CLDR {parsed_report['cldr_release']}: {parsed_report['unicode_aliases']} Unicode and "
          f"{parsed_report['transform_aliases']} transform aliases; "
          f"provider SHA256 {parsed_report['provider_data_sha256']}")


if __name__ == "__main__":
    main()
