#!/usr/bin/env python3
"""Regenerate task-document shortcut summaries from the source-validated ledger."""
from __future__ import annotations

import argparse
from collections import Counter
from pathlib import Path
import re
import subprocess
import sys

BEGIN = "<!-- shortcut-status:start -->"
END = "<!-- shortcut-status:end -->"
DOCUMENTS = ("tasks/README.md", "tasks/26-zero-failure-conformance-closure.md")
CLASSIFICATIONS = (
    "legitimate-harness-adaptation",
    "diagnostic-instrumentation",
    "semantic-shortcut",
)
REASONS = {
    "legitimate-harness-adaptation": {"upstream-harness-materialization", "suite-selection"},
    "diagnostic-instrumentation": {
        "artifact-routing", "unsupported-feature-routing", "vendored-contract-guard",
    },
    "semantic-shortcut": {
        "test-specific-materialization", "reduced-harness-helper",
        "source-shape-rewrite", "dynamic-source-substitution",
    },
}
TASK = re.compile(r"T[0-2][0-9]\Z")
KEY = re.compile(
    r"(?:path-rewrite-entrypoint|direct-path-predicate|source-text-predicate|harness-helper-reduction)"
    r"/[A-Za-z0-9_]+/[0-9]{3}\Z"
)
FINGERPRINT = re.compile(r"[0-9a-f]{64}\Z")


def ledger_counts(text: str) -> tuple[Counter[str], Counter[str]]:
    """Validate the ledger envelope; the audit independently verifies source fingerprints."""
    counts: Counter[str] = Counter()
    removals: Counter[str] = Counter()
    seen: set[str] = set()
    for line_number, line in enumerate(text.splitlines(), 1):
        if not line or line.startswith("#"):
            continue
        fields = line.split("\t")
        if len(fields) != 6:
            raise ValueError(f"ledger line {line_number}: expected exactly six TSV fields")
        key, fingerprint, classification, owner, removal, reason = fields
        if not KEY.fullmatch(key) or key in seen:
            raise ValueError(f"ledger line {line_number}: invalid or duplicate key {key!r}")
        seen.add(key)
        if not FINGERPRINT.fullmatch(fingerprint):
            raise ValueError(f"ledger line {line_number}: invalid SHA-256 fingerprint")
        if classification not in REASONS or reason not in REASONS[classification]:
            raise ValueError(f"ledger line {line_number}: invalid classification/reason pair")
        if not TASK.fullmatch(owner) or not TASK.fullmatch(removal):
            raise ValueError(f"ledger line {line_number}: owner and removal must name T00-T29")
        counts[classification] += 1
        if classification == "semantic-shortcut":
            removals[removal] += 1
    if not seen:
        raise ValueError("refusing an empty shortcut ledger")
    return counts, removals


def render_summary(text: str) -> str:
    counts, removals = ledger_counts(text)
    rows = [
        BEGIN,
        "",
        "### Current shortcut audit inventory",
        "",
        "Generated by `python3 scripts/update-shortcut-status.py --write` after the",
        "source/ledger fingerprint audit passes. The [exact inventory](../test262/backlog/shortcut-inventory.md)",
        "is the detailed evidence; these are audit observations, not failing tests or a completion percentage.",
        "",
        "| Classification | Observations |",
        "| --- | ---: |",
    ]
    rows.extend(f"| `{classification}` | {counts[classification]} |" for classification in CLASSIFICATIONS)
    rows += [f"| **Total** | **{sum(counts.values())}** |", "", "Semantic shortcuts by removal task:", ""]
    if removals:
        rows += ["| Removal task | Semantic shortcuts |", "| --- | ---: |"]
        rows.extend(f"| `{task}` | {count} |" for task, count in sorted(removals.items()))
    else:
        rows += ["No observations are currently classified as semantic shortcuts."]
    rows += [
        "",
        "A passing audit proves inventory consistency, not zero shortcuts or full Test262 conformance.",
        "Even a zero shortcut count does not establish the complete-suite, zero-failure T26 release gate.",
        "",
        END,
    ]
    return "\n".join(rows)


def replace_summary(document: str, summary: str) -> str:
    if document.count(BEGIN) != 1 or document.count(END) != 1:
        raise ValueError("task document must contain exactly one shortcut-status marker pair")
    start = document.index(BEGIN)
    end = document.index(END)
    if end < start:
        raise ValueError("shortcut-status markers are reversed")
    return document[:start] + summary + document[end + len(END):]


def refresh(root: Path, *, check: bool) -> bool:
    # Never publish counts from an unvalidated ledger. No bypass flag exists:
    # selector drift, stale inventory or an unsuccessful audit aborts before writing.
    subprocess.run([str(root / "scripts/audit-test262-shortcuts.sh"), "--check"],
                   cwd=root, check=True)
    ledger = (root / "test262/backlog/shortcut-allowlist.tsv").read_text(encoding="utf-8")
    summary = render_summary(ledger)
    changes = []
    for name in DOCUMENTS:
        document_path = root / name
        current = document_path.read_text(encoding="utf-8")
        updated = replace_summary(current, summary)
        if current != updated:
            changes.append((document_path, updated))
    if check:
        return not changes
    # Validate every target before making any edits.
    for document_path, updated in changes:
        document_path.write_text(updated, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parent.parent
    try:
        current = refresh(root, check=args.check)
    except (OSError, ValueError, subprocess.CalledProcessError) as error:
        print(f"shortcut status: {error}", file=sys.stderr)
        return 1
    if not current:
        print("shortcut status is stale; run python3 scripts/update-shortcut-status.py --write", file=sys.stderr)
        return 1
    print("shortcut status: source-validated summary is current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
