// Generated by scripts/generate-intl-keyword-aliases.py; do not edit.
// CLDR 47.0.0, commit 2ef784e3a4168bc2a43cd1b5b9839b6636f5899c.
// Unicode license and all source checksums: data/cldr-47-bcp47/.
use super::{TransformKeywordAliases, UnicodeKeywordAliases};

pub(super) const UNICODE_ALIASES: &[UnicodeKeywordAliases] = &[
    UnicodeKeywordAliases {
        key: icu_locale::extensions::unicode::key!("ca"),
        replacements: &[
            ("ethiopic-amete-alem", "ethioaa"),
            ("islamicc", "islamic-civil"),
        ],
    },
    UnicodeKeywordAliases {
        key: icu_locale::extensions::unicode::key!("kb"),
        replacements: &[("yes", "true")],
    },
    UnicodeKeywordAliases {
        key: icu_locale::extensions::unicode::key!("kc"),
        replacements: &[("yes", "true")],
    },
    UnicodeKeywordAliases {
        key: icu_locale::extensions::unicode::key!("kh"),
        replacements: &[("yes", "true")],
    },
    UnicodeKeywordAliases {
        key: icu_locale::extensions::unicode::key!("kk"),
        replacements: &[("yes", "true")],
    },
    UnicodeKeywordAliases {
        key: icu_locale::extensions::unicode::key!("kn"),
        replacements: &[("yes", "true")],
    },
    UnicodeKeywordAliases {
        key: icu_locale::extensions::unicode::key!("ks"),
        replacements: &[("primary", "level1"), ("tertiary", "level3")],
    },
    UnicodeKeywordAliases {
        key: icu_locale::extensions::unicode::key!("ms"),
        replacements: &[("imperial", "uksystem")],
    },
    UnicodeKeywordAliases {
        key: icu_locale::extensions::unicode::key!("tz"),
        replacements: &[
            ("aqams", "nzakl"),
            ("aukns", "auhba"),
            ("caffs", "cawnp"),
            ("camtr", "cator"),
            ("canpg", "cator"),
            ("capnt", "caiql"),
            ("cathu", "cator"),
            ("cayzf", "caedm"),
            ("cet", "bebru"),
            ("cnckg", "cnsha"),
            ("cnhrb", "cnsha"),
            ("cnkhg", "cnurc"),
            ("cst6cdt", "uschi"),
            ("cuba", "cuhav"),
            ("eet", "grath"),
            ("egypt", "egcai"),
            ("eire", "iedub"),
            ("est", "papty"),
            ("est5edt", "usnyc"),
            ("factory", "unk"),
            ("gaza", "gazastrp"),
            ("gmt0", "gmt"),
            ("hongkong", "hkhkg"),
            ("hst", "ushnl"),
            ("iceland", "isrey"),
            ("iran", "irthr"),
            ("israel", "jeruslm"),
            ("jamaica", "jmkin"),
            ("japan", "jptyo"),
            ("libya", "lytip"),
            ("met", "bebru"),
            ("mncoq", "mnuln"),
            ("mst", "usphx"),
            ("mst7mdt", "usden"),
            ("mxstis", "mxtij"),
            ("navajo", "usden"),
            ("poland", "plwaw"),
            ("portugal", "ptlis"),
            ("prc", "cnsha"),
            ("pst8pdt", "uslax"),
            ("roc", "twtpe"),
            ("rok", "krsel"),
            ("turkey", "trist"),
            ("uaozh", "uaiev"),
            ("uauzh", "uaiev"),
            ("uct", "utc"),
            ("umjon", "ushnl"),
            ("usnavajo", "usden"),
            ("wet", "ptlis"),
            ("zulu", "utc"),
        ],
    },
];

pub(super) const TRANSFORM_ALIASES: &[TransformKeywordAliases] = &[
    TransformKeywordAliases {
        key: icu_locale::extensions::transform::key!("d0"),
        replacements: &[("name", "charname")],
    },
    TransformKeywordAliases {
        key: icu_locale::extensions::transform::key!("m0"),
        replacements: &[
            ("beta-metsehaf", "betamets"),
            ("ies-jes", "iesjes"),
            ("names", "prprname"),
            ("tekie-alibekit", "tekieali"),
        ],
    },
];

// Composite identity covers the ICU archive, source manifest and alias rows.
pub(super) const PROVIDER_DATA_SHA256: [u8; 32] = [
    0xae, 0x86, 0x2a, 0x65, 0x8b, 0x99, 0x0b, 0xe3, 0x81, 0x7e, 0x29, 0xc4, 0x51, 0x43, 0x94, 0x90,
    0xbb, 0xa1, 0x75, 0xf0, 0x12, 0xfa, 0x71, 0xbf, 0x26, 0x39, 0x8a, 0x54, 0x5a, 0x69, 0xdf, 0xbb,
];
