// Copyright 2018 Ulf Adams
//
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//
// Ported from ryu-js 1.0.2's Ryū implementation. The Wasm emitter keeps the
// algorithm local because emitted programs cannot delegate ECMAScript
// formatting to a host.

use super::*;

const DOUBLE_MANTISSA_BITS: i64 = 52;
const DOUBLE_BIAS: i64 = 1023;
const DOUBLE_POW5_INV_BITCOUNT: i64 = 125;
const DOUBLE_POW5_BITCOUNT: i64 = 125;
const U32_MASK: i64 = 0xffff_ffff;

const POW5_INV_SPLIT: [(u64, u64); 15] = [
    (1, 2305843009213693952),
    (5955668970331000884, 1784059615882449851),
    (8982663654677661702, 1380349269358112757),
    (7286864317269821294, 2135987035920910082),
    (7005857020398200553, 1652639921975621497),
    (17965325103354776697, 1278668206209430417),
    (8928596168509315048, 1978643211784836272),
    (10075671573058298858, 1530901034580419511),
    (597001226353042382, 1184477304306571148),
    (1527430471115325346, 1832889850782397517),
    (12533209867169019542, 1418129833677084982),
    (5577825024675947042, 2194449627517475473),
    (11006974540203867551, 1697873161311732311),
    (10313493231639821582, 1313665730009899186),
    (12701016819766672773, 2032799256770390445),
];

const POW5_SPLIT: [(u64, u64); 13] = [
    (0, 1152921504606846976),
    (0, 1490116119384765625),
    (1032610780636961552, 1925929944387235853),
    (7910200175544436838, 1244603055572228341),
    (16941905809032713930, 1608611746708759036),
    (13024893955298202172, 2079081953128979843),
    (6607496772837067824, 1343575221513417750),
    (17332926989895652603, 1736530273035216783),
    (13037379183483547984, 2244412773384604712),
    (1605989338741628675, 1450417759929778918),
    (9630225068416591280, 1874621017369538693),
    (665883850346957067, 1211445438634777304),
    (14931890668723713708, 1565756531257009982),
];

const POW5: [u64; 26] = [
    1,
    5,
    25,
    125,
    625,
    3125,
    15625,
    78125,
    390625,
    1953125,
    9765625,
    48828125,
    244140625,
    1220703125,
    6103515625,
    30517578125,
    152587890625,
    762939453125,
    3814697265625,
    19073486328125,
    95367431640625,
    476837158203125,
    2384185791015625,
    11920928955078125,
    59604644775390625,
    298023223876953125,
];

const POW5_INV_OFFSETS: [u32; 19] = [
    0x54544554, 0x04055545, 0x10041000, 0x00400414, 0x40010000, 0x41155555, 0x00000454, 0x00010044,
    0x40000000, 0x44000041, 0x50454450, 0x55550054, 0x51655554, 0x40004000, 0x01000001, 0x00010500,
    0x51515411, 0x05555554, 0x00000000,
];

const POW5_OFFSETS: [u32; 21] = [
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x40000000, 0x59695995, 0x55545555, 0x56555515,
    0x41150504, 0x40555410, 0x44555145, 0x44504540, 0x45555550, 0x40004000, 0x96440440, 0x55565565,
    0x54454045, 0x40154151, 0x55559155, 0x51405555, 0x00000105,
];

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum RyuPowerTable {
    InversePow5,
    Pow5,
}

impl RyuPowerTable {
    const fn last_index(self) -> u32 {
        match self {
            Self::InversePow5 => 291,
            Self::Pow5 => 325,
        }
    }

    fn power(self, index: u32) -> (u64, u64) {
        match self {
            Self::InversePow5 => inverse_pow5(index),
            Self::Pow5 => pow5(index),
        }
    }
}

const fn pow5_bits(exponent: u32) -> u32 {
    ((exponent * 1_217_359) >> 19) + 1
}

fn pow5(index: u32) -> (u64, u64) {
    let base = index / POW5.len() as u32;
    let base_index = base * POW5.len() as u32;
    let offset = index - base_index;
    let multiplier = POW5_SPLIT[base as usize];
    if offset == 0 {
        return multiplier;
    }
    let power = POW5[offset as usize] as u128;
    let low_product = power * multiplier.0 as u128;
    let high_product = power * multiplier.1 as u128;
    let shift = pow5_bits(index) - pow5_bits(base_index);
    let correction = ((POW5_OFFSETS[(index / 16) as usize] >> ((index % 16) * 2)) & 3) as u128;
    let value = (low_product >> shift) + (high_product << (64 - shift)) + correction;
    (value as u64, (value >> 64) as u64)
}

fn inverse_pow5(index: u32) -> (u64, u64) {
    let base = index.div_ceil(POW5.len() as u32);
    let base_index = base * POW5.len() as u32;
    let offset = base_index - index;
    let multiplier = POW5_INV_SPLIT[base as usize];
    if offset == 0 {
        return multiplier;
    }
    let power = POW5[offset as usize] as u128;
    let low_product = power * multiplier.0.wrapping_sub(1) as u128;
    let high_product = power * multiplier.1 as u128;
    let shift = pow5_bits(base_index) - pow5_bits(index);
    let correction = ((POW5_INV_OFFSETS[(index / 16) as usize] >> ((index % 16) * 2)) & 3) as u128;
    let value = (low_product >> shift) + (high_product << (64 - shift)) + 1 + correction;
    (value as u64, (value >> 64) as u64)
}

impl<'a> FunctionBuilder<'a> {
    fn emit_ryu_power_lookup(
        &mut self,
        table: RyuPowerTable,
        index_local: u32,
        low_local: u32,
        high_local: u32,
        function: &mut Function,
    ) {
        function.instruction(&Instruction::I64Const(0));
        function.instruction(&Instruction::LocalSet(low_local));
        function.instruction(&Instruction::I64Const(0));
        function.instruction(&Instruction::LocalSet(high_local));
        for index in 0..=table.last_index() {
            let (low, high) = table.power(index);
            function.instruction(&Instruction::LocalGet(index_local));
            function.instruction(&Instruction::I64Const(index as i64));
            function.instruction(&Instruction::I64Eq);
            function.instruction(&Instruction::If(BlockType::Empty));
            function.instruction(&Instruction::I64Const(low as i64));
            function.instruction(&Instruction::LocalSet(low_local));
            function.instruction(&Instruction::I64Const(high as i64));
            function.instruction(&Instruction::LocalSet(high_local));
            function.instruction(&Instruction::End);
        }
        function.instruction(&Instruction::LocalGet(high_local));
        function.instruction(&Instruction::I64Eqz);
        function.instruction(&Instruction::If(BlockType::Empty));
        function.instruction(&Instruction::Unreachable);
        function.instruction(&Instruction::End);
    }

    fn emit_unsigned_multiply_128(
        &mut self,
        lhs_local: u32,
        rhs_local: u32,
        low_local: u32,
        high_local: u32,
        function: &mut Function,
    ) {
        let lhs_high_local = self.reserve_temp_local();
        let rhs_high_local = self.reserve_temp_local();
        let low_product_local = self.reserve_temp_local();
        let cross_product_local = self.reserve_temp_local();
        let cross_low_local = self.reserve_temp_local();

        function.instruction(&Instruction::LocalGet(lhs_local));
        function.instruction(&Instruction::I64Const(U32_MASK));
        function.instruction(&Instruction::I64And);
        function.instruction(&Instruction::LocalGet(rhs_local));
        function.instruction(&Instruction::I64Const(U32_MASK));
        function.instruction(&Instruction::I64And);
        function.instruction(&Instruction::I64Mul);
        function.instruction(&Instruction::LocalSet(low_product_local));
        function.instruction(&Instruction::LocalGet(lhs_local));
        function.instruction(&Instruction::I64Const(32));
        function.instruction(&Instruction::I64ShrU);
        function.instruction(&Instruction::LocalSet(lhs_high_local));
        function.instruction(&Instruction::LocalGet(rhs_local));
        function.instruction(&Instruction::I64Const(32));
        function.instruction(&Instruction::I64ShrU);
        function.instruction(&Instruction::LocalSet(rhs_high_local));
        function.instruction(&Instruction::LocalGet(lhs_high_local));
        function.instruction(&Instruction::LocalGet(rhs_local));
        function.instruction(&Instruction::I64Const(U32_MASK));
        function.instruction(&Instruction::I64And);
        function.instruction(&Instruction::I64Mul);
        function.instruction(&Instruction::LocalGet(low_product_local));
        function.instruction(&Instruction::I64Const(32));
        function.instruction(&Instruction::I64ShrU);
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::LocalSet(cross_product_local));
        function.instruction(&Instruction::LocalGet(cross_product_local));
        function.instruction(&Instruction::I64Const(U32_MASK));
        function.instruction(&Instruction::I64And);
        function.instruction(&Instruction::LocalGet(lhs_local));
        function.instruction(&Instruction::I64Const(U32_MASK));
        function.instruction(&Instruction::I64And);
        function.instruction(&Instruction::LocalGet(rhs_high_local));
        function.instruction(&Instruction::I64Mul);
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::LocalSet(cross_low_local));
        function.instruction(&Instruction::LocalGet(cross_low_local));
        function.instruction(&Instruction::I64Const(32));
        function.instruction(&Instruction::I64Shl);
        function.instruction(&Instruction::LocalGet(low_product_local));
        function.instruction(&Instruction::I64Const(U32_MASK));
        function.instruction(&Instruction::I64And);
        function.instruction(&Instruction::I64Or);
        function.instruction(&Instruction::LocalSet(low_local));
        function.instruction(&Instruction::LocalGet(lhs_high_local));
        function.instruction(&Instruction::LocalGet(rhs_high_local));
        function.instruction(&Instruction::I64Mul);
        function.instruction(&Instruction::LocalGet(cross_product_local));
        function.instruction(&Instruction::I64Const(32));
        function.instruction(&Instruction::I64ShrU);
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::LocalGet(cross_low_local));
        function.instruction(&Instruction::I64Const(32));
        function.instruction(&Instruction::I64ShrU);
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::LocalSet(high_local));

        self.release_temp_local(cross_low_local);
        self.release_temp_local(cross_product_local);
        self.release_temp_local(low_product_local);
        self.release_temp_local(rhs_high_local);
        self.release_temp_local(lhs_high_local);
    }

    fn emit_ryu_mul_shift(
        &mut self,
        value_local: u32,
        multiplier_low_local: u32,
        multiplier_high_local: u32,
        shift_local: u32,
        output_local: u32,
        function: &mut Function,
    ) {
        let low_product_low_local = self.reserve_temp_local();
        let low_product_high_local = self.reserve_temp_local();
        let high_product_low_local = self.reserve_temp_local();
        let high_product_high_local = self.reserve_temp_local();
        let sum_low_local = self.reserve_temp_local();
        let sum_high_local = self.reserve_temp_local();
        let carry_local = self.reserve_temp_local();
        let right_shift_local = self.reserve_temp_local();

        self.emit_unsigned_multiply_128(
            value_local,
            multiplier_low_local,
            low_product_low_local,
            low_product_high_local,
            function,
        );
        self.emit_unsigned_multiply_128(
            value_local,
            multiplier_high_local,
            high_product_low_local,
            high_product_high_local,
            function,
        );
        function.instruction(&Instruction::LocalGet(low_product_high_local));
        function.instruction(&Instruction::LocalGet(high_product_low_local));
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::LocalSet(sum_low_local));
        function.instruction(&Instruction::LocalGet(sum_low_local));
        function.instruction(&Instruction::LocalGet(high_product_low_local));
        function.instruction(&Instruction::I64LtU);
        function.instruction(&Instruction::I64ExtendI32U);
        function.instruction(&Instruction::LocalSet(carry_local));
        function.instruction(&Instruction::LocalGet(high_product_high_local));
        function.instruction(&Instruction::LocalGet(carry_local));
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::LocalSet(sum_high_local));
        function.instruction(&Instruction::LocalGet(shift_local));
        function.instruction(&Instruction::I64Const(64));
        function.instruction(&Instruction::I64Sub);
        function.instruction(&Instruction::LocalSet(right_shift_local));
        function.instruction(&Instruction::LocalGet(sum_low_local));
        function.instruction(&Instruction::LocalGet(right_shift_local));
        function.instruction(&Instruction::I64ShrU);
        function.instruction(&Instruction::LocalGet(sum_high_local));
        function.instruction(&Instruction::I64Const(64));
        function.instruction(&Instruction::LocalGet(right_shift_local));
        function.instruction(&Instruction::I64Sub);
        function.instruction(&Instruction::I64Shl);
        function.instruction(&Instruction::I64Or);
        function.instruction(&Instruction::LocalSet(output_local));

        self.release_temp_local(right_shift_local);
        self.release_temp_local(carry_local);
        self.release_temp_local(sum_high_local);
        self.release_temp_local(sum_low_local);
        self.release_temp_local(high_product_high_local);
        self.release_temp_local(high_product_low_local);
        self.release_temp_local(low_product_high_local);
        self.release_temp_local(low_product_low_local);
    }

    fn emit_multiple_of_power_of_five(
        &mut self,
        value_local: u32,
        exponent_local: u32,
        output_local: u32,
        function: &mut Function,
    ) {
        let divisor_local = self.reserve_temp_local();
        let index_local = self.reserve_temp_local();
        function.instruction(&Instruction::I64Const(1));
        function.instruction(&Instruction::LocalSet(divisor_local));
        function.instruction(&Instruction::I64Const(0));
        function.instruction(&Instruction::LocalSet(index_local));
        function.instruction(&Instruction::Block(BlockType::Empty));
        function.instruction(&Instruction::Loop(BlockType::Empty));
        function.instruction(&Instruction::LocalGet(index_local));
        function.instruction(&Instruction::LocalGet(exponent_local));
        function.instruction(&Instruction::I64GeU);
        function.instruction(&Instruction::BrIf(1));
        function.instruction(&Instruction::LocalGet(divisor_local));
        function.instruction(&Instruction::I64Const(5));
        function.instruction(&Instruction::I64Mul);
        function.instruction(&Instruction::LocalSet(divisor_local));
        function.instruction(&Instruction::LocalGet(index_local));
        function.instruction(&Instruction::I64Const(1));
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::LocalSet(index_local));
        function.instruction(&Instruction::Br(0));
        function.instruction(&Instruction::End);
        function.instruction(&Instruction::End);
        function.instruction(&Instruction::LocalGet(value_local));
        function.instruction(&Instruction::LocalGet(divisor_local));
        function.instruction(&Instruction::I64RemU);
        function.instruction(&Instruction::I64Eqz);
        function.instruction(&Instruction::I64ExtendI32U);
        function.instruction(&Instruction::LocalSet(output_local));
        self.release_temp_local(index_local);
        self.release_temp_local(divisor_local);
    }

    pub(super) fn emit_ryu_shortest_decimal(
        &mut self,
        absolute_bits_local: u32,
        output_mantissa_local: u32,
        output_exponent_local: u32,
        function: &mut Function,
    ) {
        let ieee_mantissa_local = self.reserve_temp_local();
        let ieee_exponent_local = self.reserve_temp_local();
        let binary_exponent_local = self.reserve_temp_local();
        let binary_mantissa_local = self.reserve_temp_local();
        let accept_bounds_local = self.reserve_temp_local();
        let scaled_mantissa_local = self.reserve_temp_local();
        let lower_boundary_shift_local = self.reserve_temp_local();
        let decimal_power_local = self.reserve_temp_local();
        let decimal_exponent_local = self.reserve_temp_local();
        let power_index_local = self.reserve_temp_local();
        let power_bits_local = self.reserve_temp_local();
        let product_shift_local = self.reserve_temp_local();
        let multiplier_low_local = self.reserve_temp_local();
        let multiplier_high_local = self.reserve_temp_local();
        let central_local = self.reserve_temp_local();
        let upper_local = self.reserve_temp_local();
        let lower_local = self.reserve_temp_local();
        let central_trailing_zeros_local = self.reserve_temp_local();
        let lower_trailing_zeros_local = self.reserve_temp_local();
        let removed_local = self.reserve_temp_local();
        let last_removed_digit_local = self.reserve_temp_local();
        let temporary_local = self.reserve_temp_local();
        let upper_quotient_local = self.reserve_temp_local();
        let lower_quotient_local = self.reserve_temp_local();
        let round_up_local = self.reserve_temp_local();

        function.instruction(&Instruction::LocalGet(absolute_bits_local));
        function.instruction(&Instruction::I64Const((1_i64 << DOUBLE_MANTISSA_BITS) - 1));
        function.instruction(&Instruction::I64And);
        function.instruction(&Instruction::LocalSet(ieee_mantissa_local));
        function.instruction(&Instruction::LocalGet(absolute_bits_local));
        function.instruction(&Instruction::I64Const(DOUBLE_MANTISSA_BITS));
        function.instruction(&Instruction::I64ShrU);
        function.instruction(&Instruction::I64Const(0x7ff));
        function.instruction(&Instruction::I64And);
        function.instruction(&Instruction::LocalSet(ieee_exponent_local));
        function.instruction(&Instruction::LocalGet(ieee_exponent_local));
        function.instruction(&Instruction::I64Eqz);
        function.instruction(&Instruction::If(BlockType::Empty));
        function.instruction(&Instruction::I64Const(
            1 - DOUBLE_BIAS - DOUBLE_MANTISSA_BITS - 2,
        ));
        function.instruction(&Instruction::LocalSet(binary_exponent_local));
        function.instruction(&Instruction::LocalGet(ieee_mantissa_local));
        function.instruction(&Instruction::LocalSet(binary_mantissa_local));
        function.instruction(&Instruction::Else);
        function.instruction(&Instruction::LocalGet(ieee_exponent_local));
        function.instruction(&Instruction::I64Const(
            DOUBLE_BIAS + DOUBLE_MANTISSA_BITS + 2,
        ));
        function.instruction(&Instruction::I64Sub);
        function.instruction(&Instruction::LocalSet(binary_exponent_local));
        function.instruction(&Instruction::LocalGet(ieee_mantissa_local));
        function.instruction(&Instruction::I64Const(1_i64 << DOUBLE_MANTISSA_BITS));
        function.instruction(&Instruction::I64Or);
        function.instruction(&Instruction::LocalSet(binary_mantissa_local));
        function.instruction(&Instruction::End);
        function.instruction(&Instruction::LocalGet(binary_mantissa_local));
        function.instruction(&Instruction::I64Const(1));
        function.instruction(&Instruction::I64And);
        function.instruction(&Instruction::I64Eqz);
        function.instruction(&Instruction::I64ExtendI32U);
        function.instruction(&Instruction::LocalSet(accept_bounds_local));
        function.instruction(&Instruction::LocalGet(binary_mantissa_local));
        function.instruction(&Instruction::I64Const(4));
        function.instruction(&Instruction::I64Mul);
        function.instruction(&Instruction::LocalSet(scaled_mantissa_local));
        function.instruction(&Instruction::LocalGet(ieee_mantissa_local));
        function.instruction(&Instruction::I64Eqz);
        function.instruction(&Instruction::I32Eqz);
        function.instruction(&Instruction::LocalGet(ieee_exponent_local));
        function.instruction(&Instruction::I64Const(1));
        function.instruction(&Instruction::I64LeU);
        function.instruction(&Instruction::I32Or);
        function.instruction(&Instruction::I64ExtendI32U);
        function.instruction(&Instruction::LocalSet(lower_boundary_shift_local));
        function.instruction(&Instruction::I64Const(0));
        function.instruction(&Instruction::LocalSet(central_trailing_zeros_local));
        function.instruction(&Instruction::I64Const(0));
        function.instruction(&Instruction::LocalSet(lower_trailing_zeros_local));

        function.instruction(&Instruction::LocalGet(binary_exponent_local));
        function.instruction(&Instruction::I64Const(0));
        function.instruction(&Instruction::I64GeS);
        function.instruction(&Instruction::If(BlockType::Empty));
        function.instruction(&Instruction::LocalGet(binary_exponent_local));
        function.instruction(&Instruction::I64Const(78_913));
        function.instruction(&Instruction::I64Mul);
        function.instruction(&Instruction::I64Const(18));
        function.instruction(&Instruction::I64ShrU);
        function.instruction(&Instruction::LocalGet(binary_exponent_local));
        function.instruction(&Instruction::I64Const(3));
        function.instruction(&Instruction::I64GtS);
        function.instruction(&Instruction::I64ExtendI32U);
        function.instruction(&Instruction::I64Sub);
        function.instruction(&Instruction::LocalTee(decimal_power_local));
        function.instruction(&Instruction::LocalSet(decimal_exponent_local));
        function.instruction(&Instruction::LocalGet(decimal_power_local));
        function.instruction(&Instruction::I64Const(1_217_359));
        function.instruction(&Instruction::I64Mul);
        function.instruction(&Instruction::I64Const(19));
        function.instruction(&Instruction::I64ShrU);
        function.instruction(&Instruction::I64Const(DOUBLE_POW5_INV_BITCOUNT));
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::LocalSet(power_bits_local));
        function.instruction(&Instruction::LocalGet(binary_exponent_local));
        function.instruction(&Instruction::I64Const(-1));
        function.instruction(&Instruction::I64Mul);
        function.instruction(&Instruction::LocalGet(decimal_power_local));
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::LocalGet(power_bits_local));
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::LocalSet(product_shift_local));
        function.instruction(&Instruction::LocalGet(decimal_power_local));
        function.instruction(&Instruction::LocalSet(power_index_local));
        self.emit_ryu_power_lookup(
            RyuPowerTable::InversePow5,
            power_index_local,
            multiplier_low_local,
            multiplier_high_local,
            function,
        );
        self.emit_ryu_interval_products(
            binary_mantissa_local,
            lower_boundary_shift_local,
            multiplier_low_local,
            multiplier_high_local,
            product_shift_local,
            central_local,
            upper_local,
            lower_local,
            function,
        );
        function.instruction(&Instruction::LocalGet(decimal_power_local));
        function.instruction(&Instruction::I64Const(21));
        function.instruction(&Instruction::I64LeU);
        function.instruction(&Instruction::If(BlockType::Empty));
        function.instruction(&Instruction::LocalGet(scaled_mantissa_local));
        function.instruction(&Instruction::I64Const(5));
        function.instruction(&Instruction::I64RemU);
        function.instruction(&Instruction::I64Eqz);
        function.instruction(&Instruction::If(BlockType::Empty));
        self.emit_multiple_of_power_of_five(
            scaled_mantissa_local,
            decimal_power_local,
            central_trailing_zeros_local,
            function,
        );
        function.instruction(&Instruction::Else);
        function.instruction(&Instruction::LocalGet(accept_bounds_local));
        function.instruction(&Instruction::I32WrapI64);
        function.instruction(&Instruction::If(BlockType::Empty));
        function.instruction(&Instruction::LocalGet(scaled_mantissa_local));
        function.instruction(&Instruction::I64Const(1));
        function.instruction(&Instruction::I64Sub);
        function.instruction(&Instruction::LocalGet(lower_boundary_shift_local));
        function.instruction(&Instruction::I64Sub);
        function.instruction(&Instruction::LocalSet(temporary_local));
        self.emit_multiple_of_power_of_five(
            temporary_local,
            decimal_power_local,
            lower_trailing_zeros_local,
            function,
        );
        function.instruction(&Instruction::Else);
        function.instruction(&Instruction::LocalGet(scaled_mantissa_local));
        function.instruction(&Instruction::I64Const(2));
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::LocalSet(temporary_local));
        self.emit_multiple_of_power_of_five(
            temporary_local,
            decimal_power_local,
            temporary_local,
            function,
        );
        function.instruction(&Instruction::LocalGet(upper_local));
        function.instruction(&Instruction::LocalGet(temporary_local));
        function.instruction(&Instruction::I64Sub);
        function.instruction(&Instruction::LocalSet(upper_local));
        function.instruction(&Instruction::End);
        function.instruction(&Instruction::End);
        function.instruction(&Instruction::End);
        function.instruction(&Instruction::Else);
        self.emit_ryu_negative_binary_exponent(
            binary_exponent_local,
            binary_mantissa_local,
            accept_bounds_local,
            scaled_mantissa_local,
            lower_boundary_shift_local,
            decimal_power_local,
            decimal_exponent_local,
            power_index_local,
            power_bits_local,
            product_shift_local,
            multiplier_low_local,
            multiplier_high_local,
            central_local,
            upper_local,
            lower_local,
            central_trailing_zeros_local,
            lower_trailing_zeros_local,
            function,
        );
        function.instruction(&Instruction::End);

        function.instruction(&Instruction::I64Const(0));
        function.instruction(&Instruction::LocalSet(removed_local));
        function.instruction(&Instruction::I64Const(0));
        function.instruction(&Instruction::LocalSet(last_removed_digit_local));
        function.instruction(&Instruction::LocalGet(lower_trailing_zeros_local));
        function.instruction(&Instruction::LocalGet(central_trailing_zeros_local));
        function.instruction(&Instruction::I64Or);
        function.instruction(&Instruction::I64Eqz);
        function.instruction(&Instruction::If(BlockType::Empty));
        self.emit_ryu_common_digit_removal(
            central_local,
            upper_local,
            lower_local,
            removed_local,
            round_up_local,
            upper_quotient_local,
            lower_quotient_local,
            output_mantissa_local,
            function,
        );
        function.instruction(&Instruction::Else);
        self.emit_ryu_trailing_zero_digit_removal(
            accept_bounds_local,
            central_local,
            upper_local,
            lower_local,
            central_trailing_zeros_local,
            lower_trailing_zeros_local,
            removed_local,
            last_removed_digit_local,
            upper_quotient_local,
            lower_quotient_local,
            output_mantissa_local,
            function,
        );
        function.instruction(&Instruction::End);
        function.instruction(&Instruction::LocalGet(decimal_exponent_local));
        function.instruction(&Instruction::LocalGet(removed_local));
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::LocalSet(output_exponent_local));

        self.release_temp_local(round_up_local);
        self.release_temp_local(lower_quotient_local);
        self.release_temp_local(upper_quotient_local);
        self.release_temp_local(temporary_local);
        self.release_temp_local(last_removed_digit_local);
        self.release_temp_local(removed_local);
        self.release_temp_local(lower_trailing_zeros_local);
        self.release_temp_local(central_trailing_zeros_local);
        self.release_temp_local(lower_local);
        self.release_temp_local(upper_local);
        self.release_temp_local(central_local);
        self.release_temp_local(multiplier_high_local);
        self.release_temp_local(multiplier_low_local);
        self.release_temp_local(product_shift_local);
        self.release_temp_local(power_bits_local);
        self.release_temp_local(power_index_local);
        self.release_temp_local(decimal_exponent_local);
        self.release_temp_local(decimal_power_local);
        self.release_temp_local(lower_boundary_shift_local);
        self.release_temp_local(scaled_mantissa_local);
        self.release_temp_local(accept_bounds_local);
        self.release_temp_local(binary_mantissa_local);
        self.release_temp_local(binary_exponent_local);
        self.release_temp_local(ieee_exponent_local);
        self.release_temp_local(ieee_mantissa_local);
    }

    pub(super) fn emit_ryu_number_to_string_payload(
        &mut self,
        payload_local: u32,
        function: &mut Function,
    ) -> Result<(), EmitError> {
        let output_local = self.reserve_temp_local();
        let absolute_bits_local = self.reserve_temp_local();
        let sign_local = self.reserve_temp_local();
        let mantissa_local = self.reserve_temp_local();
        let exponent_local = self.reserve_temp_local();

        function.instruction(&Instruction::LocalGet(payload_local));
        function.instruction(&Instruction::I64Const(i64::MAX));
        function.instruction(&Instruction::I64And);
        function.instruction(&Instruction::LocalSet(absolute_bits_local));
        function.instruction(&Instruction::LocalGet(payload_local));
        function.instruction(&Instruction::I64Const(63));
        function.instruction(&Instruction::I64ShrU);
        function.instruction(&Instruction::LocalSet(sign_local));
        function.instruction(&Instruction::LocalGet(absolute_bits_local));
        function.instruction(&Instruction::I64Const(0x7ff0_0000_0000_0000));
        function.instruction(&Instruction::I64GeU);
        function.instruction(&Instruction::If(BlockType::Empty));
        function.instruction(&Instruction::LocalGet(absolute_bits_local));
        function.instruction(&Instruction::I64Const(0x7ff0_0000_0000_0000));
        function.instruction(&Instruction::I64GtU);
        function.instruction(&Instruction::If(BlockType::Result(ValType::I64)));
        function.instruction(&Instruction::I64Const(self.strings.payload("NaN")));
        function.instruction(&Instruction::Else);
        function.instruction(&Instruction::LocalGet(sign_local));
        function.instruction(&Instruction::I32WrapI64);
        function.instruction(&Instruction::If(BlockType::Result(ValType::I64)));
        function.instruction(&Instruction::I64Const(self.strings.payload("-Infinity")));
        function.instruction(&Instruction::Else);
        function.instruction(&Instruction::I64Const(self.strings.payload("Infinity")));
        function.instruction(&Instruction::End);
        function.instruction(&Instruction::End);
        function.instruction(&Instruction::LocalSet(output_local));
        function.instruction(&Instruction::Else);
        function.instruction(&Instruction::LocalGet(absolute_bits_local));
        function.instruction(&Instruction::I64Eqz);
        function.instruction(&Instruction::If(BlockType::Empty));
        function.instruction(&Instruction::I64Const(self.strings.payload("0")));
        function.instruction(&Instruction::LocalSet(output_local));
        function.instruction(&Instruction::Else);
        self.emit_ryu_shortest_decimal(
            absolute_bits_local,
            mantissa_local,
            exponent_local,
            function,
        );
        self.emit_ecmascript_decimal_payload(
            sign_local,
            mantissa_local,
            exponent_local,
            output_local,
            function,
        )?;
        function.instruction(&Instruction::End);
        function.instruction(&Instruction::End);
        function.instruction(&Instruction::LocalGet(output_local));

        self.release_temp_local(exponent_local);
        self.release_temp_local(mantissa_local);
        self.release_temp_local(sign_local);
        self.release_temp_local(absolute_bits_local);
        self.release_temp_local(output_local);
        Ok(())
    }

    fn emit_ecmascript_decimal_payload(
        &mut self,
        sign_local: u32,
        mantissa_local: u32,
        exponent_local: u32,
        output_local: u32,
        function: &mut Function,
    ) -> Result<(), EmitError> {
        let mantissa_length_local = self.reserve_temp_local();
        let decimal_point_local = self.reserve_temp_local();
        let total_length_local = self.reserve_temp_local();
        let output_offset_local = self.reserve_temp_local();
        let number_start_local = self.reserve_temp_local();
        self.emit_count_decimal_digits_u64(mantissa_local, mantissa_length_local, function);
        function.instruction(&Instruction::LocalGet(mantissa_length_local));
        function.instruction(&Instruction::LocalGet(exponent_local));
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::LocalSet(decimal_point_local));

        function.instruction(&Instruction::LocalGet(exponent_local));
        function.instruction(&Instruction::I64Const(0));
        function.instruction(&Instruction::I64GeS);
        function.instruction(&Instruction::LocalGet(decimal_point_local));
        function.instruction(&Instruction::I64Const(21));
        function.instruction(&Instruction::I64LeS);
        function.instruction(&Instruction::I32And);
        function.instruction(&Instruction::If(BlockType::Empty));
        function.instruction(&Instruction::LocalGet(sign_local));
        function.instruction(&Instruction::LocalGet(decimal_point_local));
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::LocalSet(total_length_local));
        self.emit_heap_alloc_from_local(total_length_local, function)?;
        function.instruction(&Instruction::LocalSet(output_offset_local));
        self.emit_decimal_sign(
            sign_local,
            output_offset_local,
            number_start_local,
            function,
        );
        self.emit_write_decimal_u64(
            mantissa_local,
            number_start_local,
            mantissa_length_local,
            function,
        );
        self.emit_decimal_zero_suffix(
            number_start_local,
            mantissa_length_local,
            exponent_local,
            function,
        );
        self.emit_pack_string_payload(output_offset_local, total_length_local, function);
        function.instruction(&Instruction::LocalSet(output_local));
        function.instruction(&Instruction::Else);
        function.instruction(&Instruction::LocalGet(decimal_point_local));
        function.instruction(&Instruction::I64Const(0));
        function.instruction(&Instruction::I64GtS);
        function.instruction(&Instruction::LocalGet(decimal_point_local));
        function.instruction(&Instruction::I64Const(21));
        function.instruction(&Instruction::I64LeS);
        function.instruction(&Instruction::I32And);
        function.instruction(&Instruction::If(BlockType::Empty));
        function.instruction(&Instruction::LocalGet(sign_local));
        function.instruction(&Instruction::LocalGet(mantissa_length_local));
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::I64Const(1));
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::LocalSet(total_length_local));
        self.emit_heap_alloc_from_local(total_length_local, function)?;
        function.instruction(&Instruction::LocalSet(output_offset_local));
        self.emit_decimal_sign(
            sign_local,
            output_offset_local,
            number_start_local,
            function,
        );
        self.emit_decimal_with_internal_point(
            mantissa_local,
            mantissa_length_local,
            decimal_point_local,
            number_start_local,
            function,
        );
        self.emit_pack_string_payload(output_offset_local, total_length_local, function);
        function.instruction(&Instruction::LocalSet(output_local));
        function.instruction(&Instruction::Else);
        function.instruction(&Instruction::LocalGet(decimal_point_local));
        function.instruction(&Instruction::I64Const(-6));
        function.instruction(&Instruction::I64GtS);
        function.instruction(&Instruction::LocalGet(decimal_point_local));
        function.instruction(&Instruction::I64Const(0));
        function.instruction(&Instruction::I64LeS);
        function.instruction(&Instruction::I32And);
        function.instruction(&Instruction::If(BlockType::Empty));
        function.instruction(&Instruction::LocalGet(sign_local));
        function.instruction(&Instruction::LocalGet(mantissa_length_local));
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::I64Const(2));
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::LocalGet(decimal_point_local));
        function.instruction(&Instruction::I64Sub);
        function.instruction(&Instruction::LocalSet(total_length_local));
        self.emit_heap_alloc_from_local(total_length_local, function)?;
        function.instruction(&Instruction::LocalSet(output_offset_local));
        self.emit_decimal_sign(
            sign_local,
            output_offset_local,
            number_start_local,
            function,
        );
        self.emit_decimal_with_leading_zeros(
            mantissa_local,
            mantissa_length_local,
            decimal_point_local,
            number_start_local,
            function,
        );
        self.emit_pack_string_payload(output_offset_local, total_length_local, function);
        function.instruction(&Instruction::LocalSet(output_local));
        function.instruction(&Instruction::Else);
        self.emit_scientific_decimal_payload(
            sign_local,
            mantissa_local,
            mantissa_length_local,
            decimal_point_local,
            output_local,
            function,
        )?;
        function.instruction(&Instruction::End);
        function.instruction(&Instruction::End);
        function.instruction(&Instruction::End);

        self.release_temp_local(number_start_local);
        self.release_temp_local(output_offset_local);
        self.release_temp_local(total_length_local);
        self.release_temp_local(decimal_point_local);
        self.release_temp_local(mantissa_length_local);
        Ok(())
    }

    pub(super) fn emit_decimal_sign(
        &mut self,
        sign_local: u32,
        output_offset_local: u32,
        number_start_local: u32,
        function: &mut Function,
    ) {
        function.instruction(&Instruction::LocalGet(output_offset_local));
        function.instruction(&Instruction::LocalSet(number_start_local));
        function.instruction(&Instruction::LocalGet(sign_local));
        function.instruction(&Instruction::I32WrapI64);
        function.instruction(&Instruction::If(BlockType::Empty));
        self.store_ascii_byte_i64(output_offset_local, b'-', function);
        function.instruction(&Instruction::LocalGet(output_offset_local));
        function.instruction(&Instruction::I64Const(1));
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::LocalSet(number_start_local));
        function.instruction(&Instruction::End);
    }

    fn emit_decimal_zero_suffix(
        &mut self,
        number_start_local: u32,
        mantissa_length_local: u32,
        zero_count_local: u32,
        function: &mut Function,
    ) {
        let zero_start_local = self.reserve_temp_local();
        function.instruction(&Instruction::LocalGet(number_start_local));
        function.instruction(&Instruction::LocalGet(mantissa_length_local));
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::LocalSet(zero_start_local));
        self.emit_repeated_ascii(zero_start_local, zero_count_local, b'0', function);
        self.release_temp_local(zero_start_local);
    }

    pub(super) fn emit_repeated_ascii(
        &mut self,
        start_local: u32,
        count_local: u32,
        byte: u8,
        function: &mut Function,
    ) {
        let index_local = self.reserve_temp_local();
        let position_local = self.reserve_temp_local();
        function.instruction(&Instruction::I64Const(0));
        function.instruction(&Instruction::LocalSet(index_local));
        function.instruction(&Instruction::Block(BlockType::Empty));
        function.instruction(&Instruction::Loop(BlockType::Empty));
        function.instruction(&Instruction::LocalGet(index_local));
        function.instruction(&Instruction::LocalGet(count_local));
        function.instruction(&Instruction::I64GeU);
        function.instruction(&Instruction::BrIf(1));
        function.instruction(&Instruction::LocalGet(start_local));
        function.instruction(&Instruction::LocalGet(index_local));
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::LocalSet(position_local));
        self.store_ascii_byte_i64(position_local, byte, function);
        function.instruction(&Instruction::LocalGet(index_local));
        function.instruction(&Instruction::I64Const(1));
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::LocalSet(index_local));
        function.instruction(&Instruction::Br(0));
        function.instruction(&Instruction::End);
        function.instruction(&Instruction::End);
        self.release_temp_local(position_local);
        self.release_temp_local(index_local);
    }

    fn emit_decimal_with_internal_point(
        &mut self,
        mantissa_local: u32,
        mantissa_length_local: u32,
        decimal_point_local: u32,
        number_start_local: u32,
        function: &mut Function,
    ) {
        let shifted_start_local = self.reserve_temp_local();
        function.instruction(&Instruction::LocalGet(number_start_local));
        function.instruction(&Instruction::I64Const(1));
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::LocalSet(shifted_start_local));
        self.emit_write_decimal_u64(
            mantissa_local,
            shifted_start_local,
            mantissa_length_local,
            function,
        );
        self.emit_copy_bytes(
            shifted_start_local,
            number_start_local,
            decimal_point_local,
            function,
        );
        function.instruction(&Instruction::LocalGet(number_start_local));
        function.instruction(&Instruction::LocalGet(decimal_point_local));
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::LocalSet(shifted_start_local));
        self.store_ascii_byte_i64(shifted_start_local, b'.', function);
        self.release_temp_local(shifted_start_local);
    }

    fn emit_decimal_with_leading_zeros(
        &mut self,
        mantissa_local: u32,
        mantissa_length_local: u32,
        decimal_point_local: u32,
        number_start_local: u32,
        function: &mut Function,
    ) {
        let zero_start_local = self.reserve_temp_local();
        let zero_count_local = self.reserve_temp_local();
        let mantissa_start_local = self.reserve_temp_local();
        self.store_ascii_byte_i64(number_start_local, b'0', function);
        function.instruction(&Instruction::LocalGet(number_start_local));
        function.instruction(&Instruction::I64Const(1));
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::LocalSet(zero_start_local));
        self.store_ascii_byte_i64(zero_start_local, b'.', function);
        function.instruction(&Instruction::LocalGet(number_start_local));
        function.instruction(&Instruction::I64Const(2));
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::LocalSet(zero_start_local));
        function.instruction(&Instruction::I64Const(0));
        function.instruction(&Instruction::LocalGet(decimal_point_local));
        function.instruction(&Instruction::I64Sub);
        function.instruction(&Instruction::LocalSet(zero_count_local));
        self.emit_repeated_ascii(zero_start_local, zero_count_local, b'0', function);
        function.instruction(&Instruction::LocalGet(zero_start_local));
        function.instruction(&Instruction::LocalGet(zero_count_local));
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::LocalSet(mantissa_start_local));
        self.emit_write_decimal_u64(
            mantissa_local,
            mantissa_start_local,
            mantissa_length_local,
            function,
        );
        self.release_temp_local(mantissa_start_local);
        self.release_temp_local(zero_count_local);
        self.release_temp_local(zero_start_local);
    }

    pub(super) fn emit_scientific_decimal_payload(
        &mut self,
        sign_local: u32,
        mantissa_local: u32,
        mantissa_length_local: u32,
        decimal_point_local: u32,
        output_local: u32,
        function: &mut Function,
    ) -> Result<(), EmitError> {
        let scientific_exponent_local = self.reserve_temp_local();
        let exponent_magnitude_local = self.reserve_temp_local();
        let exponent_digits_local = self.reserve_temp_local();
        let significand_length_local = self.reserve_temp_local();
        let total_length_local = self.reserve_temp_local();
        let output_offset_local = self.reserve_temp_local();
        let number_start_local = self.reserve_temp_local();
        let shifted_start_local = self.reserve_temp_local();
        let exponent_start_local = self.reserve_temp_local();
        let first_digit_local = self.reserve_temp_local();

        function.instruction(&Instruction::LocalGet(decimal_point_local));
        function.instruction(&Instruction::I64Const(1));
        function.instruction(&Instruction::I64Sub);
        function.instruction(&Instruction::LocalSet(scientific_exponent_local));
        function.instruction(&Instruction::LocalGet(scientific_exponent_local));
        function.instruction(&Instruction::I64Const(0));
        function.instruction(&Instruction::I64LtS);
        function.instruction(&Instruction::If(BlockType::Result(ValType::I64)));
        function.instruction(&Instruction::I64Const(0));
        function.instruction(&Instruction::LocalGet(scientific_exponent_local));
        function.instruction(&Instruction::I64Sub);
        function.instruction(&Instruction::Else);
        function.instruction(&Instruction::LocalGet(scientific_exponent_local));
        function.instruction(&Instruction::End);
        function.instruction(&Instruction::LocalSet(exponent_magnitude_local));
        self.emit_count_decimal_digits_u64(
            exponent_magnitude_local,
            exponent_digits_local,
            function,
        );
        function.instruction(&Instruction::LocalGet(mantissa_length_local));
        function.instruction(&Instruction::I64Const(1));
        function.instruction(&Instruction::I64Eq);
        function.instruction(&Instruction::If(BlockType::Result(ValType::I64)));
        function.instruction(&Instruction::I64Const(1));
        function.instruction(&Instruction::Else);
        function.instruction(&Instruction::LocalGet(mantissa_length_local));
        function.instruction(&Instruction::I64Const(1));
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::End);
        function.instruction(&Instruction::LocalSet(significand_length_local));
        function.instruction(&Instruction::LocalGet(sign_local));
        function.instruction(&Instruction::LocalGet(significand_length_local));
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::I64Const(2));
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::LocalGet(exponent_digits_local));
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::LocalSet(total_length_local));
        self.emit_heap_alloc_from_local(total_length_local, function)?;
        function.instruction(&Instruction::LocalSet(output_offset_local));
        self.emit_decimal_sign(
            sign_local,
            output_offset_local,
            number_start_local,
            function,
        );
        function.instruction(&Instruction::LocalGet(mantissa_length_local));
        function.instruction(&Instruction::I64Const(1));
        function.instruction(&Instruction::I64Eq);
        function.instruction(&Instruction::If(BlockType::Empty));
        self.emit_write_decimal_u64(
            mantissa_local,
            number_start_local,
            mantissa_length_local,
            function,
        );
        function.instruction(&Instruction::Else);
        function.instruction(&Instruction::LocalGet(number_start_local));
        function.instruction(&Instruction::I64Const(1));
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::LocalSet(shifted_start_local));
        self.emit_write_decimal_u64(
            mantissa_local,
            shifted_start_local,
            mantissa_length_local,
            function,
        );
        function.instruction(&Instruction::LocalGet(shifted_start_local));
        function.instruction(&Instruction::I32WrapI64);
        function.instruction(&Instruction::I32Load8U(Self::memarg8(0)));
        function.instruction(&Instruction::I64ExtendI32U);
        function.instruction(&Instruction::LocalSet(first_digit_local));
        function.instruction(&Instruction::LocalGet(number_start_local));
        function.instruction(&Instruction::I32WrapI64);
        function.instruction(&Instruction::LocalGet(first_digit_local));
        function.instruction(&Instruction::I32WrapI64);
        function.instruction(&Instruction::I32Store8(Self::memarg8(0)));
        self.store_ascii_byte_i64(shifted_start_local, b'.', function);
        function.instruction(&Instruction::End);
        function.instruction(&Instruction::LocalGet(number_start_local));
        function.instruction(&Instruction::LocalGet(significand_length_local));
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::LocalSet(exponent_start_local));
        self.store_ascii_byte_i64(exponent_start_local, b'e', function);
        function.instruction(&Instruction::LocalGet(exponent_start_local));
        function.instruction(&Instruction::I64Const(1));
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::LocalSet(exponent_start_local));
        function.instruction(&Instruction::LocalGet(scientific_exponent_local));
        function.instruction(&Instruction::I64Const(0));
        function.instruction(&Instruction::I64LtS);
        function.instruction(&Instruction::If(BlockType::Empty));
        self.store_ascii_byte_i64(exponent_start_local, b'-', function);
        function.instruction(&Instruction::Else);
        self.store_ascii_byte_i64(exponent_start_local, b'+', function);
        function.instruction(&Instruction::End);
        function.instruction(&Instruction::LocalGet(exponent_start_local));
        function.instruction(&Instruction::I64Const(1));
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::LocalSet(exponent_start_local));
        self.emit_write_decimal_u64(
            exponent_magnitude_local,
            exponent_start_local,
            exponent_digits_local,
            function,
        );
        self.emit_pack_string_payload(output_offset_local, total_length_local, function);
        function.instruction(&Instruction::LocalSet(output_local));

        self.release_temp_local(first_digit_local);
        self.release_temp_local(exponent_start_local);
        self.release_temp_local(shifted_start_local);
        self.release_temp_local(number_start_local);
        self.release_temp_local(output_offset_local);
        self.release_temp_local(total_length_local);
        self.release_temp_local(significand_length_local);
        self.release_temp_local(exponent_digits_local);
        self.release_temp_local(exponent_magnitude_local);
        self.release_temp_local(scientific_exponent_local);
        Ok(())
    }

    #[allow(clippy::too_many_arguments)]
    fn emit_ryu_interval_products(
        &mut self,
        binary_mantissa_local: u32,
        lower_boundary_shift_local: u32,
        multiplier_low_local: u32,
        multiplier_high_local: u32,
        product_shift_local: u32,
        central_local: u32,
        upper_local: u32,
        lower_local: u32,
        function: &mut Function,
    ) {
        let boundary_local = self.reserve_temp_local();
        function.instruction(&Instruction::LocalGet(binary_mantissa_local));
        function.instruction(&Instruction::I64Const(4));
        function.instruction(&Instruction::I64Mul);
        function.instruction(&Instruction::LocalSet(boundary_local));
        self.emit_ryu_mul_shift(
            boundary_local,
            multiplier_low_local,
            multiplier_high_local,
            product_shift_local,
            central_local,
            function,
        );
        function.instruction(&Instruction::LocalGet(boundary_local));
        function.instruction(&Instruction::I64Const(2));
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::LocalSet(boundary_local));
        self.emit_ryu_mul_shift(
            boundary_local,
            multiplier_low_local,
            multiplier_high_local,
            product_shift_local,
            upper_local,
            function,
        );
        function.instruction(&Instruction::LocalGet(binary_mantissa_local));
        function.instruction(&Instruction::I64Const(4));
        function.instruction(&Instruction::I64Mul);
        function.instruction(&Instruction::I64Const(1));
        function.instruction(&Instruction::I64Sub);
        function.instruction(&Instruction::LocalGet(lower_boundary_shift_local));
        function.instruction(&Instruction::I64Sub);
        function.instruction(&Instruction::LocalSet(boundary_local));
        self.emit_ryu_mul_shift(
            boundary_local,
            multiplier_low_local,
            multiplier_high_local,
            product_shift_local,
            lower_local,
            function,
        );
        self.release_temp_local(boundary_local);
    }

    #[allow(clippy::too_many_arguments)]
    fn emit_ryu_negative_binary_exponent(
        &mut self,
        binary_exponent_local: u32,
        binary_mantissa_local: u32,
        accept_bounds_local: u32,
        scaled_mantissa_local: u32,
        lower_boundary_shift_local: u32,
        decimal_power_local: u32,
        decimal_exponent_local: u32,
        power_index_local: u32,
        power_bits_local: u32,
        product_shift_local: u32,
        multiplier_low_local: u32,
        multiplier_high_local: u32,
        central_local: u32,
        upper_local: u32,
        lower_local: u32,
        central_trailing_zeros_local: u32,
        lower_trailing_zeros_local: u32,
        function: &mut Function,
    ) {
        let negative_exponent_local = self.reserve_temp_local();
        function.instruction(&Instruction::I64Const(0));
        function.instruction(&Instruction::LocalGet(binary_exponent_local));
        function.instruction(&Instruction::I64Sub);
        function.instruction(&Instruction::LocalSet(negative_exponent_local));
        function.instruction(&Instruction::LocalGet(negative_exponent_local));
        function.instruction(&Instruction::I64Const(732_923));
        function.instruction(&Instruction::I64Mul);
        function.instruction(&Instruction::I64Const(20));
        function.instruction(&Instruction::I64ShrU);
        function.instruction(&Instruction::LocalGet(negative_exponent_local));
        function.instruction(&Instruction::I64Const(1));
        function.instruction(&Instruction::I64GtU);
        function.instruction(&Instruction::I64ExtendI32U);
        function.instruction(&Instruction::I64Sub);
        function.instruction(&Instruction::LocalSet(decimal_power_local));
        function.instruction(&Instruction::LocalGet(decimal_power_local));
        function.instruction(&Instruction::LocalGet(binary_exponent_local));
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::LocalSet(decimal_exponent_local));
        function.instruction(&Instruction::LocalGet(negative_exponent_local));
        function.instruction(&Instruction::LocalGet(decimal_power_local));
        function.instruction(&Instruction::I64Sub);
        function.instruction(&Instruction::LocalSet(power_index_local));
        function.instruction(&Instruction::LocalGet(power_index_local));
        function.instruction(&Instruction::I64Const(1_217_359));
        function.instruction(&Instruction::I64Mul);
        function.instruction(&Instruction::I64Const(19));
        function.instruction(&Instruction::I64ShrU);
        function.instruction(&Instruction::I64Const(1));
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::I64Const(DOUBLE_POW5_BITCOUNT));
        function.instruction(&Instruction::I64Sub);
        function.instruction(&Instruction::LocalSet(power_bits_local));
        function.instruction(&Instruction::LocalGet(decimal_power_local));
        function.instruction(&Instruction::LocalGet(power_bits_local));
        function.instruction(&Instruction::I64Sub);
        function.instruction(&Instruction::LocalSet(product_shift_local));
        self.emit_ryu_power_lookup(
            RyuPowerTable::Pow5,
            power_index_local,
            multiplier_low_local,
            multiplier_high_local,
            function,
        );
        self.emit_ryu_interval_products(
            binary_mantissa_local,
            lower_boundary_shift_local,
            multiplier_low_local,
            multiplier_high_local,
            product_shift_local,
            central_local,
            upper_local,
            lower_local,
            function,
        );
        function.instruction(&Instruction::LocalGet(decimal_power_local));
        function.instruction(&Instruction::I64Const(1));
        function.instruction(&Instruction::I64LeU);
        function.instruction(&Instruction::If(BlockType::Empty));
        function.instruction(&Instruction::I64Const(1));
        function.instruction(&Instruction::LocalSet(central_trailing_zeros_local));
        function.instruction(&Instruction::LocalGet(accept_bounds_local));
        function.instruction(&Instruction::I32WrapI64);
        function.instruction(&Instruction::If(BlockType::Empty));
        function.instruction(&Instruction::LocalGet(lower_boundary_shift_local));
        function.instruction(&Instruction::I64Const(1));
        function.instruction(&Instruction::I64Eq);
        function.instruction(&Instruction::I64ExtendI32U);
        function.instruction(&Instruction::LocalSet(lower_trailing_zeros_local));
        function.instruction(&Instruction::Else);
        function.instruction(&Instruction::LocalGet(upper_local));
        function.instruction(&Instruction::I64Const(1));
        function.instruction(&Instruction::I64Sub);
        function.instruction(&Instruction::LocalSet(upper_local));
        function.instruction(&Instruction::End);
        function.instruction(&Instruction::Else);
        function.instruction(&Instruction::LocalGet(decimal_power_local));
        function.instruction(&Instruction::I64Const(63));
        function.instruction(&Instruction::I64LtU);
        function.instruction(&Instruction::If(BlockType::Empty));
        function.instruction(&Instruction::LocalGet(scaled_mantissa_local));
        function.instruction(&Instruction::I64Const(1));
        function.instruction(&Instruction::LocalGet(decimal_power_local));
        function.instruction(&Instruction::I64Shl);
        function.instruction(&Instruction::I64Const(1));
        function.instruction(&Instruction::I64Sub);
        function.instruction(&Instruction::I64And);
        function.instruction(&Instruction::I64Eqz);
        function.instruction(&Instruction::I64ExtendI32U);
        function.instruction(&Instruction::LocalSet(central_trailing_zeros_local));
        function.instruction(&Instruction::End);
        function.instruction(&Instruction::End);
        self.release_temp_local(negative_exponent_local);
    }

    #[allow(clippy::too_many_arguments)]
    fn emit_ryu_common_digit_removal(
        &mut self,
        central_local: u32,
        upper_local: u32,
        lower_local: u32,
        removed_local: u32,
        round_up_local: u32,
        upper_quotient_local: u32,
        lower_quotient_local: u32,
        output_local: u32,
        function: &mut Function,
    ) {
        function.instruction(&Instruction::I64Const(0));
        function.instruction(&Instruction::LocalSet(round_up_local));
        function.instruction(&Instruction::LocalGet(upper_local));
        function.instruction(&Instruction::I64Const(100));
        function.instruction(&Instruction::I64DivU);
        function.instruction(&Instruction::LocalSet(upper_quotient_local));
        function.instruction(&Instruction::LocalGet(lower_local));
        function.instruction(&Instruction::I64Const(100));
        function.instruction(&Instruction::I64DivU);
        function.instruction(&Instruction::LocalSet(lower_quotient_local));
        function.instruction(&Instruction::LocalGet(upper_quotient_local));
        function.instruction(&Instruction::LocalGet(lower_quotient_local));
        function.instruction(&Instruction::I64GtU);
        function.instruction(&Instruction::If(BlockType::Empty));
        function.instruction(&Instruction::LocalGet(central_local));
        function.instruction(&Instruction::I64Const(100));
        function.instruction(&Instruction::I64RemU);
        function.instruction(&Instruction::I64Const(50));
        function.instruction(&Instruction::I64GeU);
        function.instruction(&Instruction::I64ExtendI32U);
        function.instruction(&Instruction::LocalSet(round_up_local));
        function.instruction(&Instruction::LocalGet(central_local));
        function.instruction(&Instruction::I64Const(100));
        function.instruction(&Instruction::I64DivU);
        function.instruction(&Instruction::LocalSet(central_local));
        function.instruction(&Instruction::LocalGet(upper_quotient_local));
        function.instruction(&Instruction::LocalSet(upper_local));
        function.instruction(&Instruction::LocalGet(lower_quotient_local));
        function.instruction(&Instruction::LocalSet(lower_local));
        function.instruction(&Instruction::I64Const(2));
        function.instruction(&Instruction::LocalSet(removed_local));
        function.instruction(&Instruction::End);
        function.instruction(&Instruction::Block(BlockType::Empty));
        function.instruction(&Instruction::Loop(BlockType::Empty));
        function.instruction(&Instruction::LocalGet(upper_local));
        function.instruction(&Instruction::I64Const(10));
        function.instruction(&Instruction::I64DivU);
        function.instruction(&Instruction::LocalSet(upper_quotient_local));
        function.instruction(&Instruction::LocalGet(lower_local));
        function.instruction(&Instruction::I64Const(10));
        function.instruction(&Instruction::I64DivU);
        function.instruction(&Instruction::LocalSet(lower_quotient_local));
        function.instruction(&Instruction::LocalGet(upper_quotient_local));
        function.instruction(&Instruction::LocalGet(lower_quotient_local));
        function.instruction(&Instruction::I64LeU);
        function.instruction(&Instruction::BrIf(1));
        function.instruction(&Instruction::LocalGet(central_local));
        function.instruction(&Instruction::I64Const(10));
        function.instruction(&Instruction::I64RemU);
        function.instruction(&Instruction::I64Const(5));
        function.instruction(&Instruction::I64GeU);
        function.instruction(&Instruction::I64ExtendI32U);
        function.instruction(&Instruction::LocalSet(round_up_local));
        function.instruction(&Instruction::LocalGet(central_local));
        function.instruction(&Instruction::I64Const(10));
        function.instruction(&Instruction::I64DivU);
        function.instruction(&Instruction::LocalSet(central_local));
        function.instruction(&Instruction::LocalGet(upper_quotient_local));
        function.instruction(&Instruction::LocalSet(upper_local));
        function.instruction(&Instruction::LocalGet(lower_quotient_local));
        function.instruction(&Instruction::LocalSet(lower_local));
        function.instruction(&Instruction::LocalGet(removed_local));
        function.instruction(&Instruction::I64Const(1));
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::LocalSet(removed_local));
        function.instruction(&Instruction::Br(0));
        function.instruction(&Instruction::End);
        function.instruction(&Instruction::End);
        function.instruction(&Instruction::LocalGet(central_local));
        function.instruction(&Instruction::LocalGet(lower_local));
        function.instruction(&Instruction::I64Eq);
        function.instruction(&Instruction::LocalGet(round_up_local));
        function.instruction(&Instruction::I32WrapI64);
        function.instruction(&Instruction::I32Or);
        function.instruction(&Instruction::I64ExtendI32U);
        function.instruction(&Instruction::LocalGet(central_local));
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::LocalSet(output_local));
    }

    #[allow(clippy::too_many_arguments)]
    fn emit_ryu_trailing_zero_digit_removal(
        &mut self,
        accept_bounds_local: u32,
        central_local: u32,
        upper_local: u32,
        lower_local: u32,
        central_trailing_zeros_local: u32,
        lower_trailing_zeros_local: u32,
        removed_local: u32,
        last_removed_digit_local: u32,
        upper_quotient_local: u32,
        lower_quotient_local: u32,
        output_local: u32,
        function: &mut Function,
    ) {
        function.instruction(&Instruction::Block(BlockType::Empty));
        function.instruction(&Instruction::Loop(BlockType::Empty));
        function.instruction(&Instruction::LocalGet(upper_local));
        function.instruction(&Instruction::I64Const(10));
        function.instruction(&Instruction::I64DivU);
        function.instruction(&Instruction::LocalSet(upper_quotient_local));
        function.instruction(&Instruction::LocalGet(lower_local));
        function.instruction(&Instruction::I64Const(10));
        function.instruction(&Instruction::I64DivU);
        function.instruction(&Instruction::LocalSet(lower_quotient_local));
        function.instruction(&Instruction::LocalGet(upper_quotient_local));
        function.instruction(&Instruction::LocalGet(lower_quotient_local));
        function.instruction(&Instruction::I64LeU);
        function.instruction(&Instruction::BrIf(1));
        function.instruction(&Instruction::LocalGet(lower_local));
        function.instruction(&Instruction::I64Const(10));
        function.instruction(&Instruction::I64RemU);
        function.instruction(&Instruction::I64Eqz);
        function.instruction(&Instruction::LocalGet(lower_trailing_zeros_local));
        function.instruction(&Instruction::I32WrapI64);
        function.instruction(&Instruction::I32And);
        function.instruction(&Instruction::I64ExtendI32U);
        function.instruction(&Instruction::LocalSet(lower_trailing_zeros_local));
        function.instruction(&Instruction::LocalGet(last_removed_digit_local));
        function.instruction(&Instruction::I64Eqz);
        function.instruction(&Instruction::LocalGet(central_trailing_zeros_local));
        function.instruction(&Instruction::I32WrapI64);
        function.instruction(&Instruction::I32And);
        function.instruction(&Instruction::I64ExtendI32U);
        function.instruction(&Instruction::LocalSet(central_trailing_zeros_local));
        function.instruction(&Instruction::LocalGet(central_local));
        function.instruction(&Instruction::I64Const(10));
        function.instruction(&Instruction::I64RemU);
        function.instruction(&Instruction::LocalSet(last_removed_digit_local));
        function.instruction(&Instruction::LocalGet(central_local));
        function.instruction(&Instruction::I64Const(10));
        function.instruction(&Instruction::I64DivU);
        function.instruction(&Instruction::LocalSet(central_local));
        function.instruction(&Instruction::LocalGet(upper_quotient_local));
        function.instruction(&Instruction::LocalSet(upper_local));
        function.instruction(&Instruction::LocalGet(lower_quotient_local));
        function.instruction(&Instruction::LocalSet(lower_local));
        function.instruction(&Instruction::LocalGet(removed_local));
        function.instruction(&Instruction::I64Const(1));
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::LocalSet(removed_local));
        function.instruction(&Instruction::Br(0));
        function.instruction(&Instruction::End);
        function.instruction(&Instruction::End);
        function.instruction(&Instruction::LocalGet(lower_trailing_zeros_local));
        function.instruction(&Instruction::I32WrapI64);
        function.instruction(&Instruction::If(BlockType::Empty));
        function.instruction(&Instruction::Block(BlockType::Empty));
        function.instruction(&Instruction::Loop(BlockType::Empty));
        function.instruction(&Instruction::LocalGet(lower_local));
        function.instruction(&Instruction::I64Const(10));
        function.instruction(&Instruction::I64RemU);
        function.instruction(&Instruction::I64Eqz);
        function.instruction(&Instruction::I32Eqz);
        function.instruction(&Instruction::BrIf(1));
        function.instruction(&Instruction::LocalGet(last_removed_digit_local));
        function.instruction(&Instruction::I64Eqz);
        function.instruction(&Instruction::LocalGet(central_trailing_zeros_local));
        function.instruction(&Instruction::I32WrapI64);
        function.instruction(&Instruction::I32And);
        function.instruction(&Instruction::I64ExtendI32U);
        function.instruction(&Instruction::LocalSet(central_trailing_zeros_local));
        function.instruction(&Instruction::LocalGet(central_local));
        function.instruction(&Instruction::I64Const(10));
        function.instruction(&Instruction::I64RemU);
        function.instruction(&Instruction::LocalSet(last_removed_digit_local));
        function.instruction(&Instruction::LocalGet(central_local));
        function.instruction(&Instruction::I64Const(10));
        function.instruction(&Instruction::I64DivU);
        function.instruction(&Instruction::LocalSet(central_local));
        function.instruction(&Instruction::LocalGet(upper_local));
        function.instruction(&Instruction::I64Const(10));
        function.instruction(&Instruction::I64DivU);
        function.instruction(&Instruction::LocalSet(upper_local));
        function.instruction(&Instruction::LocalGet(lower_local));
        function.instruction(&Instruction::I64Const(10));
        function.instruction(&Instruction::I64DivU);
        function.instruction(&Instruction::LocalSet(lower_local));
        function.instruction(&Instruction::LocalGet(removed_local));
        function.instruction(&Instruction::I64Const(1));
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::LocalSet(removed_local));
        function.instruction(&Instruction::Br(0));
        function.instruction(&Instruction::End);
        function.instruction(&Instruction::End);
        function.instruction(&Instruction::End);
        function.instruction(&Instruction::LocalGet(central_trailing_zeros_local));
        function.instruction(&Instruction::I32WrapI64);
        function.instruction(&Instruction::LocalGet(last_removed_digit_local));
        function.instruction(&Instruction::I64Const(5));
        function.instruction(&Instruction::I64Eq);
        function.instruction(&Instruction::I32And);
        function.instruction(&Instruction::LocalGet(central_local));
        function.instruction(&Instruction::I64Const(2));
        function.instruction(&Instruction::I64RemU);
        function.instruction(&Instruction::I64Eqz);
        function.instruction(&Instruction::I32And);
        function.instruction(&Instruction::If(BlockType::Empty));
        function.instruction(&Instruction::I64Const(4));
        function.instruction(&Instruction::LocalSet(last_removed_digit_local));
        function.instruction(&Instruction::End);
        function.instruction(&Instruction::LocalGet(central_local));
        function.instruction(&Instruction::LocalGet(lower_local));
        function.instruction(&Instruction::I64Eq);
        function.instruction(&Instruction::LocalGet(accept_bounds_local));
        function.instruction(&Instruction::I64Eqz);
        function.instruction(&Instruction::LocalGet(lower_trailing_zeros_local));
        function.instruction(&Instruction::I64Eqz);
        function.instruction(&Instruction::I32Or);
        function.instruction(&Instruction::I32And);
        function.instruction(&Instruction::LocalGet(last_removed_digit_local));
        function.instruction(&Instruction::I64Const(5));
        function.instruction(&Instruction::I64GeU);
        function.instruction(&Instruction::I32Or);
        function.instruction(&Instruction::I64ExtendI32U);
        function.instruction(&Instruction::LocalGet(central_local));
        function.instruction(&Instruction::I64Add);
        function.instruction(&Instruction::LocalSet(output_local));
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn table_hash(table: RyuPowerTable) -> u64 {
        let mut hash = 0xcbf2_9ce4_8422_2325_u64;
        for index in 0..=table.last_index() {
            let (low, high) = table.power(index);
            for byte in low.to_le_bytes().into_iter().chain(high.to_le_bytes()) {
                hash ^= u64::from(byte);
                hash = hash.wrapping_mul(0x100_0000_01b3);
            }
        }
        hash
    }

    #[test]
    fn generated_power_tables_match_ryu_js_1_0_2() {
        // Digests are computed over every little-endian (low, high) pair in
        // ryu-js 1.0.2's d2s_full_table.rs, restricted to binary64's reachable
        // inverse-power domain 0..=291 and power domain 0..=325.
        assert_eq!(
            table_hash(RyuPowerTable::InversePow5),
            0xca4b_f530_9787_5660
        );
        assert_eq!(table_hash(RyuPowerTable::Pow5), 0x0a8f_348f_7cf6_1776);
    }
}
