//! Exact actual exporter output; no baked default-sort substitution for search.
use icu_collator::provider::*;
use icu_normalizer::provider::{NormalizerNfdDataV1, NormalizerNfdTablesV1};
use icu_provider::prelude::*;

include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated/mod.rs"));

/// Immutable provider for the exact pinned exported collation and NFD data.
pub struct PinnedCollatorProvider;
make_provider!(PinnedCollatorProvider);
impl_collation_root_v1!(PinnedCollatorProvider);
impl_collation_tailoring_v1!(PinnedCollatorProvider, ITER);
impl_collation_metadata_v1!(PinnedCollatorProvider, ITER);
impl_collation_diacritics_v1!(PinnedCollatorProvider, ITER);
impl_collation_jamo_v1!(PinnedCollatorProvider);
impl_collation_reordering_v1!(PinnedCollatorProvider, ITER);
impl_collation_special_primaries_v1!(PinnedCollatorProvider);
impl_normalizer_nfd_data_v1!(PinnedCollatorProvider);
impl_normalizer_nfd_tables_v1!(PinnedCollatorProvider);

// The captured exporter misspells BTreeSet in its unused singleton ITER arms.
// Preserve those pinned generated bytes and enumerate the sole exact key here.
macro_rules! singleton_ids {
    ($marker:ty) => {
        impl IterableDataProvider<$marker> for PinnedCollatorProvider {
            fn iter_ids(
                &self,
            ) -> Result<std::collections::BTreeSet<DataIdentifierCow<'static>>, DataError> {
                Ok([DataIdentifierCow::default()].into_iter().collect())
            }
        }
    };
}
singleton_ids!(CollationRootV1);
singleton_ids!(CollationJamoV1);
singleton_ids!(CollationSpecialPrimariesV1);
singleton_ids!(NormalizerNfdDataV1);
singleton_ids!(NormalizerNfdTablesV1);
