//! Immutable pinned Collator data generated by the captured ICU4X exporter.
//!
//! The native Intl kernel validates locale and marker associations before using
//! this provider. JavaScript semantics remain in the compiled Wasm consumer.
#![deny(unsafe_code)]

// Exact exporter macros contain static-data constructors. Keep their expansion
// in this private module; handwritten product crates retain workspace forbid.
#[allow(unsafe_code)]
mod baked;

pub use baked::PinnedCollatorProvider;
