// Generated by scripts/generate-intl-displaynames-profile.py.
// This is the payload identity; the final provider recipe must also bind native/producer owners.
pub const DISPLAY_NAMES_DATA_SHA256: [u8; 32] = [
    0xb1, 0xc2, 0x0f, 0xcf, 0x2d, 0xf0, 0xdb, 0xf7, 0xd6, 0xdb, 0x8e, 0xca, 0x38, 0xb6, 0x12, 0x41,
    0x86, 0x54, 0xf5, 0xe7, 0x53, 0x69, 0xfd, 0x9a, 0x08, 0xb2, 0x71, 0x4c, 0x3b, 0xf9, 0xd2, 0xa4,
];
pub(super) const SOURCE_MANIFEST_SHA256: &str =
    "d9ef53250bb02002a2c3520a5f4aab029bbbdc12da909c782af0f0f81c9a80d5";
pub(super) const BCP47_MANIFEST_SHA256: &str =
    "71a427fdc899544cb7ff29bc84c0c0f1fb5c29cbd80a35336ace332004235ff7";
